# RHEL OSS odiglet image.
# Expects named bake contexts: builder, common-binaries, agents-builder.
# COPY order: heavy/stable layers first, odiglet binary last (changes most often).
# Builder must be built with RHEL=true so /licenses is populated.

ARG ODIGLET_BASE_IMAGE=registry.odigos.io/odiglet-base:v1.20

# Note that we do not pass --platform=$BUILDPLATFORM here because we want to have the base image for all target architecture - each contains the corresponding rsync binary for the target arch.
FROM ${ODIGLET_BASE_IMAGE} AS rsync-base

FROM registry.access.redhat.com/ubi9/ubi-micro:latest AS odiglet-rhel
ARG VERSION
ARG RELEASE
ARG SUMMARY
ARG DESCRIPTION
LABEL "name"="Odiglet"
LABEL "vendor"="Odigos"
LABEL "maintainer"="Odigos"
LABEL "version"=$VERSION
LABEL "release"=$RELEASE
LABEL "summary"=$SUMMARY
LABEL "description"=$DESCRIPTION
# Copy statically compiled rsync (no shared libraries needed)
COPY --from=rsync-base /usr/bin/rsync /usr/bin/rsync
# This one is heavy (takes a while to copy since it's many hundreds of MB) so do it first.
COPY --from=agents-builder /instrumentations/ /instrumentations/
COPY --from=common-binaries /tmp/grpc_health_probe /root/grpc_health_probe
COPY --from=common-binaries /go/src/github.com/odigos-io/odigos/deviceplugin/deviceplugin /root/deviceplugin
COPY --from=common-binaries /go/src/github.com/odigos-io/odigos/odiglet/odigos-csi-driver /root/odigos-csi-driver
COPY --from=builder /go/src/github.com/odigos-io/odigos/odiglet/licenses /licenses
COPY --from=builder /go/src/github.com/odigos-io/odigos/odiglet/LICENSE /licenses/.
# This one changes most often so do it last.
COPY --from=builder /go/src/github.com/odigos-io/odigos/odiglet/odiglet /root/odiglet
# make sure we run as non root user
# this is required when this container is added to a pod that has runAsNonRoot: true
USER 65532:65532
CMD ["/root/odiglet"]
