// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/odigossqlquery component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigossqlquery")
	ScopeName = "github.com/odigos-io/odigos/collector/processors/odigossqlqueryprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
