{{- if and .Values.insights.enabled (include "odigos.secretExists" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odigos-insights
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
{{- end }}
