// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/odigosvmprofileattrsprocessor component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigosvmprofileattrsprocessor")
	ScopeName = "github.com/odigos-io/odigos/collector/processors/odigosvmprofileattrsprocessor"
)

const (
	ProfilesStability = component.StabilityLevelAlpha
)
