{{- if and .Values.interrogation.enabled (include "odigos.secretExists" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odigos-interrogation
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["odigos.io"]
    resources: ["instrumentationrules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
