//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package instrumentationrules

import (
	"github.com/odigos-io/odigos/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeAttributes) DeepCopyInto(out *CodeAttributes) {
	*out = *in
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = new(bool)
		**out = **in
	}
	if in.FilePath != nil {
		in, out := &in.FilePath, &out.FilePath
		*out = new(bool)
		**out = **in
	}
	if in.Function != nil {
		in, out := &in.Function, &out.Function
		*out = new(bool)
		**out = **in
	}
	if in.LineNumber != nil {
		in, out := &in.LineNumber, &out.LineNumber
		*out = new(bool)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(bool)
		**out = **in
	}
	if in.Stacktrace != nil {
		in, out := &in.Stacktrace, &out.Stacktrace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeAttributes.
func (in *CodeAttributes) DeepCopy() *CodeAttributes {
	if in == nil {
		return nil
	}
	out := new(CodeAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomInstrumentations) DeepCopyInto(out *CustomInstrumentations) {
	*out = *in
	if in.Golang != nil {
		in, out := &in.Golang, &out.Golang
		*out = make([]GolangCustomProbe, len(*in))
		copy(*out, *in)
	}
	if in.Java != nil {
		in, out := &in.Java, &out.Java
		*out = make([]JavaCustomProbe, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomInstrumentations.
func (in *CustomInstrumentations) DeepCopy() *CustomInstrumentations {
	if in == nil {
		return nil
	}
	out := new(CustomInstrumentations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbQueryPayloadCollection) DeepCopyInto(out *DbQueryPayloadCollection) {
	*out = *in
	if in.MaxPayloadLength != nil {
		in, out := &in.MaxPayloadLength, &out.MaxPayloadLength
		*out = new(int64)
		**out = **in
	}
	if in.DropPartialPayloads != nil {
		in, out := &in.DropPartialPayloads, &out.DropPartialPayloads
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbQueryPayloadCollection.
func (in *DbQueryPayloadCollection) DeepCopy() *DbQueryPayloadCollection {
	if in == nil {
		return nil
	}
	out := new(DbQueryPayloadCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GolangCustomProbe) DeepCopyInto(out *GolangCustomProbe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GolangCustomProbe.
func (in *GolangCustomProbe) DeepCopy() *GolangCustomProbe {
	if in == nil {
		return nil
	}
	out := new(GolangCustomProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadSamplingFallbackFraction) DeepCopyInto(out *HeadSamplingFallbackFraction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadSamplingFallbackFraction.
func (in *HeadSamplingFallbackFraction) DeepCopy() *HeadSamplingFallbackFraction {
	if in == nil {
		return nil
	}
	out := new(HeadSamplingFallbackFraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpHeadersCollection) DeepCopyInto(out *HttpHeadersCollection) {
	*out = *in
	if in.HeaderKeys != nil {
		in, out := &in.HeaderKeys, &out.HeaderKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpHeadersCollection.
func (in *HttpHeadersCollection) DeepCopy() *HttpHeadersCollection {
	if in == nil {
		return nil
	}
	out := new(HttpHeadersCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpPayloadCollection) DeepCopyInto(out *HttpPayloadCollection) {
	*out = *in
	if in.MimeTypes != nil {
		in, out := &in.MimeTypes, &out.MimeTypes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.MaxPayloadLength != nil {
		in, out := &in.MaxPayloadLength, &out.MaxPayloadLength
		*out = new(int64)
		**out = **in
	}
	if in.DropPartialPayloads != nil {
		in, out := &in.DropPartialPayloads, &out.DropPartialPayloads
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpPayloadCollection.
func (in *HttpPayloadCollection) DeepCopy() *HttpPayloadCollection {
	if in == nil {
		return nil
	}
	out := new(HttpPayloadCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaCustomProbe) DeepCopyInto(out *JavaCustomProbe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaCustomProbe.
func (in *JavaCustomProbe) DeepCopy() *JavaCustomProbe {
	if in == nil {
		return nil
	}
	out := new(JavaCustomProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingPayloadCollection) DeepCopyInto(out *MessagingPayloadCollection) {
	*out = *in
	if in.MaxPayloadLength != nil {
		in, out := &in.MaxPayloadLength, &out.MaxPayloadLength
		*out = new(int64)
		**out = **in
	}
	if in.DropPartialPayloads != nil {
		in, out := &in.DropPartialPayloads, &out.DropPartialPayloads
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingPayloadCollection.
func (in *MessagingPayloadCollection) DeepCopy() *MessagingPayloadCollection {
	if in == nil {
		return nil
	}
	out := new(MessagingPayloadCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelDistros) DeepCopyInto(out *OtelDistros) {
	*out = *in
	if in.OtelDistroNames != nil {
		in, out := &in.OtelDistroNames, &out.OtelDistroNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelDistros.
func (in *OtelDistros) DeepCopy() *OtelDistros {
	if in == nil {
		return nil
	}
	out := new(OtelDistros)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelSdks) DeepCopyInto(out *OtelSdks) {
	*out = *in
	if in.OtelSdkByLanguage != nil {
		in, out := &in.OtelSdkByLanguage, &out.OtelSdkByLanguage
		*out = make(map[common.ProgrammingLanguage]common.OtelSdk, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelSdks.
func (in *OtelSdks) DeepCopy() *OtelSdks {
	if in == nil {
		return nil
	}
	out := new(OtelSdks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PayloadCollection) DeepCopyInto(out *PayloadCollection) {
	*out = *in
	if in.HttpRequest != nil {
		in, out := &in.HttpRequest, &out.HttpRequest
		*out = new(HttpPayloadCollection)
		(*in).DeepCopyInto(*out)
	}
	if in.HttpResponse != nil {
		in, out := &in.HttpResponse, &out.HttpResponse
		*out = new(HttpPayloadCollection)
		(*in).DeepCopyInto(*out)
	}
	if in.DbQuery != nil {
		in, out := &in.DbQuery, &out.DbQuery
		*out = new(DbQueryPayloadCollection)
		(*in).DeepCopyInto(*out)
	}
	if in.Messaging != nil {
		in, out := &in.Messaging, &out.Messaging
		*out = new(MessagingPayloadCollection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PayloadCollection.
func (in *PayloadCollection) DeepCopy() *PayloadCollection {
	if in == nil {
		return nil
	}
	out := new(PayloadCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceConfig) DeepCopyInto(out *TraceConfig) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceConfig.
func (in *TraceConfig) DeepCopy() *TraceConfig {
	if in == nil {
		return nil
	}
	out := new(TraceConfig)
	in.DeepCopyInto(out)
	return out
}
