{{- if and .Values.security.enabled (include "odigos.secretExists" .) }}
apiVersion: v1
kind: Service
metadata:
  name: odigos-security-clickhouse
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: odigos-security-clickhouse
    odigos.io/system-object: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: odigos-security-clickhouse
  ports:
    - name: native
      port: 9000
      targetPort: 9000
    - name: http
      port: 8123
      targetPort: 8123
{{- end }}
