// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigos_workload_config")
	ScopeName = "github.com/odigos-io/odigos/collector/extension/odigosworkloadconfigextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
