apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: odigos-scheduler
    odigos.io/system-object: "true"
  name: odigos-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: odigos-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: odigos-scheduler
    spec:
      containers:
      - name: manager
        {{ $imageTag := .Values.image.tag | default .Chart.AppVersion }}
        image: {{ template "utils.imageName" (dict "Values" .Values "Release" .Release "Component" "scheduler" "Tag" $imageTag) }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      {{ include "odigos.renderPullSecrets" . | nindent 6 }}
