// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Action struct {
	ID         string        `json:"id"`
	Type       ActionType    `json:"type"`
	Name       *string       `json:"name,omitempty"`
	Notes      *string       `json:"notes,omitempty"`
	Disabled   bool          `json:"disabled"`
	Signals    []SignalType  `json:"signals"`
	Fields     *ActionFields `json:"fields"`
	Conditions []*Condition  `json:"conditions,omitempty"`
}

type ActionFields struct {
	CollectContainerAttributes  *bool                     `json:"collectContainerAttributes,omitempty"`
	CollectReplicaSetAttributes *bool                     `json:"collectReplicaSetAttributes,omitempty"`
	CollectWorkloadID           *bool                     `json:"collectWorkloadId,omitempty"`
	CollectClusterID            *bool                     `json:"collectClusterId,omitempty"`
	LabelsAttributes            []*K8sLabelAttribute      `json:"labelsAttributes,omitempty"`
	AnnotationsAttributes       []*K8sAnnotationAttribute `json:"annotationsAttributes,omitempty"`
	ClusterAttributes           []*ClusterAttribute       `json:"clusterAttributes,omitempty"`
	OverwriteExistingValues     *bool                     `json:"overwriteExistingValues,omitempty"`
	AttributeNamesToDelete      []string                  `json:"attributeNamesToDelete,omitempty"`
	Renames                     *string                   `json:"renames,omitempty"`
	PiiCategories               []string                  `json:"piiCategories,omitempty"`
	SamplingPercentage          *string                   `json:"samplingPercentage,omitempty"`
	FallbackSamplingRatio       *int                      `json:"fallbackSamplingRatio,omitempty"`
	EndpointsFilters            []*HTTPRouteFilter        `json:"endpointsFilters,omitempty"`
	ServicesNameFilters         []*ServiceNameFilter      `json:"servicesNameFilters,omitempty"`
	AttributeFilters            []*SpanAttributeFilter    `json:"attributeFilters,omitempty"`
}

type ActionFieldsInput struct {
	CollectContainerAttributes  *bool                          `json:"collectContainerAttributes,omitempty"`
	CollectReplicaSetAttributes *bool                          `json:"collectReplicaSetAttributes,omitempty"`
	CollectWorkloadID           *bool                          `json:"collectWorkloadId,omitempty"`
	CollectClusterID            *bool                          `json:"collectClusterId,omitempty"`
	LabelsAttributes            []*K8sLabelAttributeInput      `json:"labelsAttributes,omitempty"`
	AnnotationsAttributes       []*K8sAnnotationAttributeInput `json:"annotationsAttributes,omitempty"`
	ClusterAttributes           []*ClusterAttributeInput       `json:"clusterAttributes,omitempty"`
	OverwriteExistingValues     *bool                          `json:"overwriteExistingValues,omitempty"`
	AttributeNamesToDelete      []string                       `json:"attributeNamesToDelete,omitempty"`
	Renames                     *string                        `json:"renames,omitempty"`
	PiiCategories               []string                       `json:"piiCategories,omitempty"`
	SamplingPercentage          *string                        `json:"samplingPercentage,omitempty"`
	FallbackSamplingRatio       *int                           `json:"fallbackSamplingRatio,omitempty"`
	EndpointsFilters            []*HTTPRouteFilterInput        `json:"endpointsFilters,omitempty"`
	ServicesNameFilters         []*ServiceNameFilterInput      `json:"servicesNameFilters,omitempty"`
	AttributeFilters            []*SpanAttributeFilterInput    `json:"attributeFilters,omitempty"`
}

type ActionInput struct {
	Type     ActionType         `json:"type"`
	Name     *string            `json:"name,omitempty"`
	Notes    *string            `json:"notes,omitempty"`
	Disabled bool               `json:"disabled"`
	Signals  []SignalType       `json:"signals"`
	Fields   *ActionFieldsInput `json:"fields"`
}

type AgentsInitContainerResourcesConfig struct {
	RequestCPUm      *int `json:"requestCPUm,omitempty"`
	LimitCPUm        *int `json:"limitCPUm,omitempty"`
	RequestMemoryMiB *int `json:"requestMemoryMiB,omitempty"`
	LimitMemoryMiB   *int `json:"limitMemoryMiB,omitempty"`
}

type APIToken struct {
	Token     string  `json:"token"`
	Name      string  `json:"name"`
	IssuedAt  int     `json:"issuedAt"`
	ExpiresAt int     `json:"expiresAt"`
	Message   *string `json:"message,omitempty"`
}

type AttributeFilters struct {
	ServiceName           string                     `json:"serviceName"`
	AttributeKey          string                     `json:"attributeKey"`
	FallbackSamplingRatio float64                    `json:"fallbackSamplingRatio"`
	Condition             *AttributeFiltersCondition `json:"condition"`
}

type AttributeFiltersCondition struct {
	StringCondition  *StringCondition  `json:"stringCondition,omitempty"`
	NumberCondition  *NumberCondition  `json:"numberCondition,omitempty"`
	BooleanCondition *BooleanCondition `json:"booleanCondition,omitempty"`
	JSONCondition    *JSONCondition    `json:"jsonCondition,omitempty"`
}

type AttributeFiltersConditionInput struct {
	StringCondition  *StringConditionInput  `json:"stringCondition,omitempty"`
	NumberCondition  *NumberConditionInput  `json:"numberCondition,omitempty"`
	BooleanCondition *BooleanConditionInput `json:"booleanCondition,omitempty"`
	JSONCondition    *JSONConditionInput    `json:"jsonCondition,omitempty"`
}

type BooleanCondition struct {
	Operation     BooleanOperation `json:"operation"`
	ExpectedValue bool             `json:"expectedValue"`
}

type BooleanConditionInput struct {
	Operation     BooleanOperation `json:"operation"`
	ExpectedValue bool             `json:"expectedValue"`
}

type ClusterAttribute struct {
	AttributeName        string `json:"attributeName"`
	AttributeStringValue string `json:"attributeStringValue"`
}

type ClusterAttributeInput struct {
	AttributeName        string `json:"attributeName"`
	AttributeStringValue string `json:"attributeStringValue"`
}

type ClusterCollectorAnalyze struct {
	Enabled              *EntityProperty `json:"enabled"`
	CollectorGroup       *EntityProperty `json:"collectorGroup"`
	Deployed             *EntityProperty `json:"deployed,omitempty"`
	DeployedError        *EntityProperty `json:"deployedError,omitempty"`
	CollectorReady       *EntityProperty `json:"collectorReady,omitempty"`
	DeploymentCreated    *EntityProperty `json:"deploymentCreated"`
	ExpectedReplicas     *EntityProperty `json:"expectedReplicas,omitempty"`
	HealthyReplicas      *EntityProperty `json:"healthyReplicas,omitempty"`
	FailedReplicas       *EntityProperty `json:"failedReplicas,omitempty"`
	FailedReplicasReason *EntityProperty `json:"failedReplicasReason,omitempty"`
}

type CodeAttributes struct {
	Column     *bool `json:"column,omitempty"`
	FilePath   *bool `json:"filePath,omitempty"`
	Function   *bool `json:"function,omitempty"`
	LineNumber *bool `json:"lineNumber,omitempty"`
	Namespace  *bool `json:"namespace,omitempty"`
	Stacktrace *bool `json:"stacktrace,omitempty"`
}

type CodeAttributesInput struct {
	Column     *bool `json:"column,omitempty"`
	FilePath   *bool `json:"filePath,omitempty"`
	Function   *bool `json:"function,omitempty"`
	LineNumber *bool `json:"lineNumber,omitempty"`
	Namespace  *bool `json:"namespace,omitempty"`
	Stacktrace *bool `json:"stacktrace,omitempty"`
}

type CollectorDaemonSetInfo struct {
	Status            WorkloadRolloutStatus `json:"status"`
	Nodes             *NodesSummary         `json:"nodes"`
	Resources         *Resources            `json:"resources,omitempty"`
	ImageVersion      *string               `json:"imageVersion,omitempty"`
	LastRolloutAt     *string               `json:"lastRolloutAt,omitempty"`
	RolloutInProgress bool                  `json:"rolloutInProgress"`
	ManifestYaml      string                `json:"manifestYAML"`
	ConfigMapYaml     string                `json:"configMapYAML"`
}

type CollectorGatewayConfig struct {
	MinReplicas                *int    `json:"minReplicas,omitempty"`
	MaxReplicas                *int    `json:"maxReplicas,omitempty"`
	RequestMemoryMiB           *int    `json:"requestMemoryMiB,omitempty"`
	LimitMemoryMiB             *int    `json:"limitMemoryMiB,omitempty"`
	RequestCPUm                *int    `json:"requestCPUm,omitempty"`
	LimitCPUm                  *int    `json:"limitCPUm,omitempty"`
	MemoryLimiterLimitMiB      *int    `json:"memoryLimiterLimitMiB,omitempty"`
	MemoryLimiterSpikeLimitMiB *int    `json:"memoryLimiterSpikeLimitMiB,omitempty"`
	GoMemLimitMiB              *int    `json:"goMemLimitMiB,omitempty"`
	ServiceGraphDisabled       *bool   `json:"serviceGraphDisabled,omitempty"`
	ClusterMetricsEnabled      *bool   `json:"clusterMetricsEnabled,omitempty"`
	HTTPSProxyAddress          *string `json:"httpsProxyAddress,omitempty"`
	NodeSelector               *string `json:"nodeSelector,omitempty"`
}

type CollectorNodeConfig struct {
	CollectorOwnMetricsPort    *int                `json:"collectorOwnMetricsPort,omitempty"`
	RequestMemoryMiB           *int                `json:"requestMemoryMiB,omitempty"`
	LimitMemoryMiB             *int                `json:"limitMemoryMiB,omitempty"`
	RequestCPUm                *int                `json:"requestCPUm,omitempty"`
	LimitCPUm                  *int                `json:"limitCPUm,omitempty"`
	MemoryLimiterLimitMiB      *int                `json:"memoryLimiterLimitMiB,omitempty"`
	MemoryLimiterSpikeLimitMiB *int                `json:"memoryLimiterSpikeLimitMiB,omitempty"`
	GoMemLimitMiB              *int                `json:"goMemLimitMiB,omitempty"`
	K8sNodeLogsDirectory       *string             `json:"k8sNodeLogsDirectory,omitempty"`
	EnableDataCompression      *bool               `json:"enableDataCompression,omitempty"`
	OtlpExporterConfiguration  *OtlpExporterConfig `json:"otlpExporterConfiguration,omitempty"`
}

type CollectorPodMetrics struct {
	MetricsAcceptedRps float64 `json:"metricsAcceptedRps"`
	MetricsDroppedRps  float64 `json:"metricsDroppedRps"`
	ExporterSuccessRps float64 `json:"exporterSuccessRps"`
	ExporterFailedRps  float64 `json:"exporterFailedRps"`
	Window             string  `json:"window"`
	LastScrape         *string `json:"lastScrape,omitempty"`
}

type ComputePlatform struct {
	ComputePlatformType  ComputePlatformType    `json:"computePlatformType"`
	APITokens            []*APIToken            `json:"apiTokens"`
	K8sActualNamespaces  []*K8sActualNamespace  `json:"k8sActualNamespaces"`
	K8sActualNamespace   *K8sActualNamespace    `json:"k8sActualNamespace,omitempty"`
	Sources              []*K8sActualSource     `json:"sources"`
	Source               *K8sActualSource       `json:"source"`
	Destinations         []*Destination         `json:"destinations"`
	Actions              []*Action              `json:"actions"`
	InstrumentationRules []*InstrumentationRule `json:"instrumentationRules"`
	DataStreams          []*DataStream          `json:"dataStreams"`
}

type Condition struct {
	Status             ConditionStatus `json:"status"`
	Type               string          `json:"type"`
	Reason             *string         `json:"reason,omitempty"`
	Message            *string         `json:"message,omitempty"`
	LastTransitionTime *string         `json:"lastTransitionTime,omitempty"`
}

type Config struct {
	Readonly              bool                `json:"readonly"`
	PlatformType          ComputePlatformType `json:"platformType"`
	Tier                  Tier                `json:"tier"`
	OdigosVersion         string              `json:"odigosVersion"`
	InstallationMethod    string              `json:"installationMethod"`
	InstallationStatus    InstallationStatus  `json:"installationStatus"`
	ClusterName           *string             `json:"clusterName,omitempty"`
	IsCentralProxyRunning *bool               `json:"isCentralProxyRunning,omitempty"`
}

type ContainerAgentConfigAnalyze struct {
	ContainerName  *EntityProperty `json:"containerName"`
	AgentEnabled   *EntityProperty `json:"agentEnabled"`
	Reason         *EntityProperty `json:"reason,omitempty"`
	Message        *EntityProperty `json:"message,omitempty"`
	OtelDistroName *EntityProperty `json:"otelDistroName,omitempty"`
}

type ContainerOverview struct {
	Name        string                   `json:"name"`
	Image       *string                  `json:"image,omitempty"`
	Status      ContainerLifecycleStatus `json:"status"`
	StateReason *string                  `json:"stateReason,omitempty"`
	Ready       bool                     `json:"ready"`
	Started     bool                     `json:"started"`
	Restarts    int                      `json:"restarts"`
	StartedAt   *string                  `json:"startedAt,omitempty"`
	Resources   *Resources               `json:"resources,omitempty"`
}

type ContainerRuntimeInfoAnalyze struct {
	ContainerName  *EntityProperty   `json:"containerName"`
	Language       *EntityProperty   `json:"language"`
	RuntimeVersion *EntityProperty   `json:"runtimeVersion"`
	EnvVars        []*EntityProperty `json:"envVars"`
}

type CustomInstrumentations struct {
	Golang []*GolangCustomProbe `json:"golang,omitempty"`
	Java   []*JavaCustomProbe   `json:"java,omitempty"`
}

type CustomInstrumentationsInput struct {
	Golang []*GolangCustomProbeInput `json:"golang,omitempty"`
	Java   []*JavaCustomProbeInput   `json:"java,omitempty"`
}

type CustomReadDataLabel struct {
	Condition string `json:"condition"`
	Title     string `json:"title"`
	Value     string `json:"value"`
}

type DataStream struct {
	Name string `json:"name"`
}

type DataStreamInput struct {
	Name string `json:"name"`
}

type DbQueryPayloadCollection struct {
	MaxPayloadLength    *int  `json:"maxPayloadLength,omitempty"`
	DropPartialPayloads *bool `json:"dropPartialPayloads,omitempty"`
}

type DbQueryPayloadCollectionInput struct {
	MaxPayloadLength    *int  `json:"maxPayloadLength,omitempty"`
	DropPartialPayloads *bool `json:"dropPartialPayloads,omitempty"`
}

type DesiredConditionStatus struct {
	Name       string               `json:"name"`
	Status     DesiredStateProgress `json:"status"`
	ReasonEnum *string              `json:"reasonEnum,omitempty"`
	Message    string               `json:"message"`
}

type Destination struct {
	ID              string                        `json:"id"`
	Type            string                        `json:"type"`
	Name            string                        `json:"name"`
	Disabled        bool                          `json:"disabled"`
	DataStreamNames []*string                     `json:"dataStreamNames"`
	ExportedSignals *ExportedSignals              `json:"exportedSignals"`
	Fields          string                        `json:"fields"`
	DestinationType *DestinationTypesCategoryItem `json:"destinationType"`
	Conditions      []*Condition                  `json:"conditions,omitempty"`
}

type DestinationDetails struct {
	Type      string `json:"type"`
	URLString string `json:"urlString"`
	Fields    string `json:"fields"`
}

type DestinationFieldYamlProperties struct {
	Name                 string                 `json:"name"`
	DisplayName          string                 `json:"displayName"`
	ComponentType        string                 `json:"componentType"`
	ComponentProperties  string                 `json:"componentProperties"`
	Secret               bool                   `json:"secret"`
	InitialValue         string                 `json:"initialValue"`
	RenderCondition      []string               `json:"renderCondition"`
	HideFromReadData     []string               `json:"hideFromReadData"`
	CustomReadDataLabels []*CustomReadDataLabel `json:"customReadDataLabels"`
}

type DestinationInput struct {
	Name              string                `json:"name"`
	Type              string                `json:"type"`
	CurrentStreamName string                `json:"currentStreamName"`
	ExportedSignals   *ExportedSignalsInput `json:"exportedSignals"`
	Fields            []*FieldInput         `json:"fields"`
	Disabled          *bool                 `json:"disabled,omitempty"`
}

type DestinationTypesCategoryItem struct {
	Type                    string                            `json:"type"`
	DisplayName             string                            `json:"displayName"`
	ImageURL                string                            `json:"imageUrl"`
	SupportedSignals        *SupportedSignals                 `json:"supportedSignals"`
	TestConnectionSupported bool                              `json:"testConnectionSupported"`
	Fields                  []*DestinationFieldYamlProperties `json:"fields"`
}

type DestinationsCategory struct {
	Name        string                          `json:"name"`
	Description string                          `json:"description"`
	Items       []*DestinationTypesCategoryItem `json:"items"`
}

type DiagnoseInput struct {
	IncludeProfiles          *bool    `json:"includeProfiles,omitempty"`
	IncludeMetrics           *bool    `json:"includeMetrics,omitempty"`
	IncludeSourceWorkloads   *bool    `json:"includeSourceWorkloads,omitempty"`
	SourceWorkloadNamespaces []string `json:"sourceWorkloadNamespaces,omitempty"`
}

type DiagnoseResponse struct {
	Stats                    *DiagnoseStats `json:"stats"`
	IncludeProfiles          bool           `json:"includeProfiles"`
	IncludeMetrics           bool           `json:"includeMetrics"`
	IncludeSourceWorkloads   bool           `json:"includeSourceWorkloads"`
	SourceWorkloadNamespaces []string       `json:"sourceWorkloadNamespaces"`
}

type DiagnoseStats struct {
	FileCount      int    `json:"fileCount"`
	TotalSizeBytes int    `json:"totalSizeBytes"`
	TotalSizeHuman string `json:"totalSizeHuman"`
}

type DistroParam struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type EffectiveConfig struct {
	ConfigVersion                    int                                 `json:"configVersion"`
	TelemetryEnabled                 *bool                               `json:"telemetryEnabled,omitempty"`
	OpenshiftEnabled                 *bool                               `json:"openshiftEnabled,omitempty"`
	IgnoredNamespaces                []string                            `json:"ignoredNamespaces,omitempty"`
	IgnoredContainers                []string                            `json:"ignoredContainers,omitempty"`
	IgnoreOdigosNamespace            *bool                               `json:"ignoreOdigosNamespace,omitempty"`
	Psp                              *bool                               `json:"psp,omitempty"`
	ImagePrefix                      *string                             `json:"imagePrefix,omitempty"`
	SkipWebhookIssuerCreation        *bool                               `json:"skipWebhookIssuerCreation,omitempty"`
	CollectorGateway                 *CollectorGatewayConfig             `json:"collectorGateway,omitempty"`
	CollectorNode                    *CollectorNodeConfig                `json:"collectorNode,omitempty"`
	Profiles                         []string                            `json:"profiles,omitempty"`
	AllowConcurrentAgents            *bool                               `json:"allowConcurrentAgents,omitempty"`
	UIMode                           *UIMode                             `json:"uiMode,omitempty"`
	UIPaginationLimit                *int                                `json:"uiPaginationLimit,omitempty"`
	UIRemoteURL                      *string                             `json:"uiRemoteUrl,omitempty"`
	CentralBackendURL                *string                             `json:"centralBackendURL,omitempty"`
	ClusterName                      *string                             `json:"clusterName,omitempty"`
	MountMethod                      *MountMethod                        `json:"mountMethod,omitempty"`
	CustomContainerRuntimeSocketPath *string                             `json:"customContainerRuntimeSocketPath,omitempty"`
	AgentEnvVarsInjectionMethod      *EnvInjectionMethod                 `json:"agentEnvVarsInjectionMethod,omitempty"`
	UserInstrumentationEnvs          *UserInstrumentationEnvsConfig      `json:"userInstrumentationEnvs,omitempty"`
	NodeSelector                     *string                             `json:"nodeSelector,omitempty"`
	KarpenterEnabled                 *bool                               `json:"karpenterEnabled,omitempty"`
	Rollout                          *RolloutConfig                      `json:"rollout,omitempty"`
	RollbackDisabled                 *bool                               `json:"rollbackDisabled,omitempty"`
	RollbackGraceTime                *string                             `json:"rollbackGraceTime,omitempty"`
	RollbackStabilityWindow          *string                             `json:"rollbackStabilityWindow,omitempty"`
	Oidc                             *OidcConfig                         `json:"oidc,omitempty"`
	OdigletHealthProbeBindPort       *int                                `json:"odigletHealthProbeBindPort,omitempty"`
	GoAutoOffsetsCron                *string                             `json:"goAutoOffsetsCron,omitempty"`
	GoAutoOffsetsMode                *string                             `json:"goAutoOffsetsMode,omitempty"`
	ClickhouseJSONTypeEnabled        *bool                               `json:"clickhouseJsonTypeEnabled,omitempty"`
	CheckDeviceHealthBeforeInjection *bool                               `json:"checkDeviceHealthBeforeInjection,omitempty"`
	ResourceSizePreset               *string                             `json:"resourceSizePreset,omitempty"`
	WaspEnabled                      *bool                               `json:"waspEnabled,omitempty"`
	MetricsSources                   *MetricsSourceConfig                `json:"metricsSources,omitempty"`
	AgentsInitContainerResources     *AgentsInitContainerResourcesConfig `json:"agentsInitContainerResources,omitempty"`
	TraceIDSuffix                    *string                             `json:"traceIdSuffix,omitempty"`
	AllowedTestConnectionHosts       []string                            `json:"allowedTestConnectionHosts,omitempty"`
	OdigosOwnTelemetryStore          *OdigosOwnTelemetryConfig           `json:"odigosOwnTelemetryStore,omitempty"`
	ImagePullSecrets                 []string                            `json:"imagePullSecrets,omitempty"`
}

type EntityProperty struct {
	Name    string  `json:"name"`
	Value   string  `json:"value"`
	Status  *string `json:"status,omitempty"`
	Explain *string `json:"explain,omitempty"`
}

type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type ExportedSignals struct {
	Traces  bool `json:"traces"`
	Metrics bool `json:"metrics"`
	Logs    bool `json:"logs"`
}

type ExportedSignalsInput struct {
	Traces  bool `json:"traces"`
	Metrics bool `json:"metrics"`
	Logs    bool `json:"logs"`
}

type FieldInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type GatewayDeploymentInfo struct {
	Status            WorkloadRolloutStatus        `json:"status"`
	Hpa               *HorizontalPodAutoscalerInfo `json:"hpa,omitempty"`
	Resources         *Resources                   `json:"resources,omitempty"`
	ImageVersion      *string                      `json:"imageVersion,omitempty"`
	LastRolloutAt     *string                      `json:"lastRolloutAt,omitempty"`
	RolloutInProgress bool                         `json:"rolloutInProgress"`
	ManifestYaml      string                       `json:"manifestYAML"`
	ConfigMapYaml     string                       `json:"configMapYAML"`
}

type GetDestinationCategories struct {
	Categories []*DestinationsCategory `json:"categories"`
}

type GolangCustomProbe struct {
	PackageName        *string `json:"packageName,omitempty"`
	FunctionName       *string `json:"functionName,omitempty"`
	ReceiverName       *string `json:"receiverName,omitempty"`
	ReceiverMethodName *string `json:"receiverMethodName,omitempty"`
}

type GolangCustomProbeInput struct {
	PackageName        *string `json:"packageName,omitempty"`
	FunctionName       *string `json:"functionName,omitempty"`
	ReceiverName       *string `json:"receiverName,omitempty"`
	ReceiverMethodName *string `json:"receiverMethodName,omitempty"`
}

type HeadersCollection struct {
	HeaderKeys []*string `json:"headerKeys,omitempty"`
}

type HeadersCollectionInput struct {
	HeaderKeys []*string `json:"headerKeys,omitempty"`
}

type HorizontalPodAutoscalerInfo struct {
	Min        *int         `json:"min,omitempty"`
	Max        *int         `json:"max,omitempty"`
	Current    *int         `json:"current,omitempty"`
	Desired    *int         `json:"desired,omitempty"`
	Conditions []*Condition `json:"conditions,omitempty"`
}

type HTTPPayloadCollection struct {
	MimeTypes           []*string `json:"mimeTypes,omitempty"`
	MaxPayloadLength    *int      `json:"maxPayloadLength,omitempty"`
	DropPartialPayloads *bool     `json:"dropPartialPayloads,omitempty"`
}

type HTTPPayloadCollectionInput struct {
	MimeTypes           []*string `json:"mimeTypes,omitempty"`
	MaxPayloadLength    *int      `json:"maxPayloadLength,omitempty"`
	DropPartialPayloads *bool     `json:"dropPartialPayloads,omitempty"`
}

type HTTPRouteFilter struct {
	HTTPRoute               string  `json:"httpRoute"`
	ServiceName             string  `json:"serviceName"`
	MinimumLatencyThreshold int     `json:"minimumLatencyThreshold"`
	FallbackSamplingRatio   float64 `json:"fallbackSamplingRatio"`
}

type HTTPRouteFilterInput struct {
	HTTPRoute               string  `json:"httpRoute"`
	ServiceName             string  `json:"serviceName"`
	MinimumLatencyThreshold int     `json:"minimumLatencyThreshold"`
	FallbackSamplingRatio   float64 `json:"fallbackSamplingRatio"`
}

type InstrumentationInstanceAnalyze struct {
	Healthy               *EntityProperty   `json:"healthy"`
	Message               *EntityProperty   `json:"message,omitempty"`
	IdentifyingAttributes []*EntityProperty `json:"identifyingAttributes"`
}

type InstrumentationInstanceComponent struct {
	Name                     string                     `json:"name"`
	Type                     *string                    `json:"type,omitempty"`
	Healthy                  *bool                      `json:"healthy,omitempty"`
	Message                  *string                    `json:"message,omitempty"`
	LastStatusTime           *string                    `json:"lastStatusTime,omitempty"`
	NonIdentifyingAttributes []*NonIdentifyingAttribute `json:"nonIdentifyingAttributes"`
}

type InstrumentationLibraryGlobalID struct {
	Name     string               `json:"name"`
	SpanKind *SpanKind            `json:"spanKind,omitempty"`
	Language *ProgrammingLanguage `json:"language,omitempty"`
}

type InstrumentationLibraryGlobalIDInput struct {
	Name     string               `json:"name"`
	SpanKind *SpanKind            `json:"spanKind,omitempty"`
	Language *ProgrammingLanguage `json:"language,omitempty"`
}

type InstrumentationRule struct {
	Type                     InstrumentationRuleType           `json:"type"`
	RuleID                   string                            `json:"ruleId"`
	RuleName                 *string                           `json:"ruleName,omitempty"`
	Notes                    *string                           `json:"notes,omitempty"`
	Disabled                 *bool                             `json:"disabled,omitempty"`
	Mutable                  bool                              `json:"mutable"`
	ProfileName              string                            `json:"profileName"`
	Workloads                []*PodWorkload                    `json:"workloads,omitempty"`
	InstrumentationLibraries []*InstrumentationLibraryGlobalID `json:"instrumentationLibraries,omitempty"`
	Conditions               []*Condition                      `json:"conditions,omitempty"`
	CodeAttributes           *CodeAttributes                   `json:"codeAttributes,omitempty"`
	HeadersCollection        *HeadersCollection                `json:"headersCollection,omitempty"`
	PayloadCollection        *PayloadCollection                `json:"payloadCollection,omitempty"`
	CustomInstrumentations   *CustomInstrumentations           `json:"customInstrumentations,omitempty"`
}

type InstrumentationRuleInput struct {
	RuleName                 *string                                `json:"ruleName,omitempty"`
	Notes                    *string                                `json:"notes,omitempty"`
	Disabled                 *bool                                  `json:"disabled,omitempty"`
	Workloads                []*PodWorkloadInput                    `json:"workloads,omitempty"`
	InstrumentationLibraries []*InstrumentationLibraryGlobalIDInput `json:"instrumentationLibraries,omitempty"`
	CodeAttributes           *CodeAttributesInput                   `json:"codeAttributes,omitempty"`
	HeadersCollection        *HeadersCollectionInput                `json:"headersCollection,omitempty"`
	PayloadCollection        *PayloadCollectionInput                `json:"payloadCollection,omitempty"`
	CustomInstrumentations   *CustomInstrumentationsInput           `json:"customInstrumentations,omitempty"`
}

type InstrumentationSourcesAnalyze struct {
	Instrumented     *EntityProperty `json:"instrumented"`
	Workload         *EntityProperty `json:"workload,omitempty"`
	Namespace        *EntityProperty `json:"namespace,omitempty"`
	InstrumentedText *EntityProperty `json:"instrumentedText,omitempty"`
}

type JavaCustomProbe struct {
	ClassName  *string `json:"className,omitempty"`
	MethodName *string `json:"methodName,omitempty"`
}

type JavaCustomProbeInput struct {
	ClassName  *string `json:"className,omitempty"`
	MethodName *string `json:"methodName,omitempty"`
}

type JSONCondition struct {
	Operation     JSONOperation `json:"operation"`
	ExpectedValue *string       `json:"expectedValue,omitempty"`
	JSONPath      *string       `json:"jsonPath,omitempty"`
}

type JSONConditionInput struct {
	Operation     JSONOperation `json:"operation"`
	ExpectedValue *string       `json:"expectedValue,omitempty"`
	JSONPath      *string       `json:"jsonPath,omitempty"`
}

type K8sActualNamespace struct {
	Name            string             `json:"name"`
	Selected        bool               `json:"selected"`
	DataStreamNames []*string          `json:"dataStreamNames"`
	Sources         []*K8sActualSource `json:"sources"`
}

type K8sActualSource struct {
	Namespace                 string             `json:"namespace"`
	Name                      string             `json:"name"`
	Kind                      K8sResourceKind    `json:"kind"`
	DataStreamNames           []*string          `json:"dataStreamNames"`
	NumberOfInstances         *int               `json:"numberOfInstances,omitempty"`
	Selected                  *bool              `json:"selected,omitempty"`
	OtelServiceName           *string            `json:"otelServiceName,omitempty"`
	Containers                []*SourceContainer `json:"containers,omitempty"`
	Conditions                []*Condition       `json:"conditions,omitempty"`
	ManifestYaml              *string            `json:"manifestYAML,omitempty"`
	InstrumentationConfigYaml *string            `json:"instrumentationConfigYAML,omitempty"`
}

type K8sAnnotationAttribute struct {
	AnnotationKey string              `json:"annotationKey"`
	AttributeKey  string              `json:"attributeKey"`
	From          *K8sAttributesFrom  `json:"from,omitempty"`
	FromSources   []K8sAttributesFrom `json:"fromSources,omitempty"`
}

type K8sAnnotationAttributeInput struct {
	AnnotationKey string              `json:"annotationKey"`
	AttributeKey  string              `json:"attributeKey"`
	From          *K8sAttributesFrom  `json:"from,omitempty"`
	FromSources   []K8sAttributesFrom `json:"fromSources,omitempty"`
}

type K8sDesiredNamespaceInput struct {
	AutoInstrument *bool `json:"autoInstrument,omitempty"`
}

type K8sDesiredSourceInput struct {
	ServiceName    *string `json:"serviceName,omitempty"`
	AutoInstrument *bool   `json:"autoInstrument,omitempty"`
}

type K8sHealthProbesSamplingConfig struct {
	Enabled        *bool    `json:"enabled,omitempty"`
	KeepPercentage *float64 `json:"keepPercentage,omitempty"`
}

type K8sHealthProbesSamplingConfigInput struct {
	Enabled        *bool    `json:"enabled,omitempty"`
	KeepPercentage *float64 `json:"keepPercentage,omitempty"`
}

type K8sLabelAttribute struct {
	LabelKey     string              `json:"labelKey"`
	AttributeKey string              `json:"attributeKey"`
	From         *K8sAttributesFrom  `json:"from,omitempty"`
	FromSources  []K8sAttributesFrom `json:"fromSources,omitempty"`
}

type K8sLabelAttributeInput struct {
	LabelKey     string              `json:"labelKey"`
	AttributeKey string              `json:"attributeKey"`
	From         *K8sAttributesFrom  `json:"from,omitempty"`
	FromSources  []K8sAttributesFrom `json:"fromSources,omitempty"`
}

type K8sNamespaceID struct {
	Name string `json:"name"`
}

type K8sSourceID struct {
	Namespace string          `json:"namespace"`
	Kind      K8sResourceKind `json:"kind"`
	Name      string          `json:"name"`
}

type K8sWorkload struct {
	ID                         *K8sWorkloadID                       `json:"id"`
	ServiceName                *string                              `json:"serviceName,omitempty"`
	WorkloadOdigosHealthStatus *DesiredConditionStatus              `json:"workloadOdigosHealthStatus"`
	Conditions                 *K8sWorkloadConditions               `json:"conditions"`
	MarkedForInstrumentation   *K8sWorkloadMarkedForInstrumentation `json:"markedForInstrumentation"`
	RuntimeInfo                *K8sWorkloadRuntimeInfo              `json:"runtimeInfo,omitempty"`
	AgentEnabled               *K8sWorkloadAgentEnabled             `json:"agentEnabled,omitempty"`
	Rollout                    *K8sWorkloadRollout                  `json:"rollout,omitempty"`
	Containers                 []*K8sWorkloadContainer              `json:"containers,omitempty"`
	Pods                       []*K8sWorkloadPod                    `json:"pods,omitempty"`
	PodsAgentInjectionStatus   *DesiredConditionStatus              `json:"podsAgentInjectionStatus"`
	PodsHealthStatus           *DesiredConditionStatus              `json:"podsHealthStatus"`
	WorkloadHealthStatus       *DesiredConditionStatus              `json:"workloadHealthStatus,omitempty"`
	ProcessesHealthStatus      *DesiredConditionStatus              `json:"processesHealthStatus"`
	TelemetryMetrics           []*K8sWorkloadTelemetryMetrics       `json:"telemetryMetrics"`
	RollbackOccurred           bool                                 `json:"rollbackOccurred"`
}

type K8sWorkloadAgentEnabled struct {
	AgentEnabled  bool                                `json:"agentEnabled"`
	EnabledStatus *DesiredConditionStatus             `json:"enabledStatus"`
	Containers    []*K8sWorkloadAgentEnabledContainer `json:"containers,omitempty"`
}

type K8sWorkloadAgentEnabledContainer struct {
	ContainerName      string                                   `json:"containerName"`
	AgentEnabled       bool                                     `json:"agentEnabled"`
	AgentEnabledStatus *DesiredConditionStatus                  `json:"agentEnabledStatus"`
	OtelDistroName     *string                                  `json:"otelDistroName,omitempty"`
	EnvInjectionMethod *string                                  `json:"envInjectionMethod,omitempty"`
	DistroParams       []*DistroParam                           `json:"distroParams,omitempty"`
	Traces             *K8sWorkloadAgentEnabledContainerTraces  `json:"traces,omitempty"`
	Metrics            *K8sWorkloadAgentEnabledContainerMetrics `json:"metrics,omitempty"`
	Logs               *K8sWorkloadAgentEnabledContainerLogs    `json:"logs,omitempty"`
}

type K8sWorkloadAgentEnabledContainerLogs struct {
	Enabled bool `json:"enabled"`
}

type K8sWorkloadAgentEnabledContainerMetrics struct {
	Enabled bool `json:"enabled"`
}

type K8sWorkloadAgentEnabledContainerTraces struct {
	Enabled bool `json:"enabled"`
}

type K8sWorkloadConditions struct {
	RuntimeDetection      *DesiredConditionStatus `json:"runtimeDetection,omitempty"`
	AgentInjectionEnabled *DesiredConditionStatus `json:"agentInjectionEnabled,omitempty"`
	Rollout               *DesiredConditionStatus `json:"rollout,omitempty"`
	AgentInjected         *DesiredConditionStatus `json:"agentInjected,omitempty"`
	ProcessesAgentHealth  *DesiredConditionStatus `json:"processesAgentHealth,omitempty"`
	ExpectingTelemetry    *DesiredConditionStatus `json:"expectingTelemetry,omitempty"`
}

type K8sWorkloadContainer struct {
	ContainerName    string                                           `json:"containerName"`
	RuntimeInfo      *K8sWorkloadRuntimeInfoContainer                 `json:"runtimeInfo,omitempty"`
	AgentEnabled     *K8sWorkloadAgentEnabledContainer                `json:"agentEnabled,omitempty"`
	Overrides        *K8sWorkloadContainerOverrides                   `json:"overrides,omitempty"`
	AgentConfig      *K8sWorkloadContainerAgentConfig                 `json:"agentConfig,omitempty"`
	Instrumentations []*K8sWorkloadPodContainerProcessInstrumentation `json:"instrumentations,omitempty"`
}

type K8sWorkloadContainerAgentConfig struct {
	Traces *K8sWorkloadContainerAgentConfigTraces `json:"traces,omitempty"`
}

type K8sWorkloadContainerAgentConfigTraces struct {
	HeadSampling *K8sWorkloadContainerAgentConfigTracesHeadSampling `json:"headSampling,omitempty"`
}

type K8sWorkloadContainerAgentConfigTracesHeadSampling struct {
	Checks             []*K8sWorkloadContainerAgentConfigTracesHeadSamplingCheck `json:"checks,omitempty"`
	FallbackPercentage float64                                                   `json:"fallbackPercentage"`
}

type K8sWorkloadContainerAgentConfigTracesHeadSamplingCheck struct {
	Conditions []*K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckCondition `json:"conditions,omitempty"`
	Percentage float64                                                            `json:"percentage"`
}

type K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckCondition struct {
	Key      string                                                                  `json:"key"`
	Operator K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator `json:"operator"`
	Value    string                                                                  `json:"value"`
}

type K8sWorkloadContainerOverrides struct {
	ContainerName string                           `json:"containerName"`
	RuntimeInfo   *K8sWorkloadRuntimeInfoContainer `json:"runtimeInfo,omitempty"`
}

type K8sWorkloadID struct {
	Namespace string          `json:"namespace"`
	Kind      K8sResourceKind `json:"kind"`
	Name      string          `json:"name"`
}

type K8sWorkloadMarkedForInstrumentation struct {
	MarkedForInstrumentation *bool  `json:"markedForInstrumentation,omitempty"`
	DecisionEnum             string `json:"decisionEnum"`
	Message                  string `json:"message"`
}

type K8sWorkloadPod struct {
	PodName                        string                     `json:"podName"`
	NodeName                       string                     `json:"nodeName"`
	StartTime                      string                     `json:"startTime"`
	AgentInjected                  bool                       `json:"agentInjected"`
	StartedPostAgentMetaHashChange *bool                      `json:"startedPostAgentMetaHashChange,omitempty"`
	AgentInjectedStatus            *DesiredConditionStatus    `json:"agentInjectedStatus"`
	RunningLatestWorkloadRevision  *string                    `json:"runningLatestWorkloadRevision,omitempty"`
	PodHealthStatus                *DesiredConditionStatus    `json:"podHealthStatus"`
	Containers                     []*K8sWorkloadPodContainer `json:"containers"`
}

type K8sWorkloadPodContainer struct {
	ContainerName                   string                            `json:"containerName"`
	OdigosInstrumentationDeviceName *string                           `json:"odigosInstrumentationDeviceName,omitempty"`
	OtelDistroName                  *string                           `json:"otelDistroName,omitempty"`
	Started                         *bool                             `json:"started,omitempty"`
	Ready                           *bool                             `json:"ready,omitempty"`
	IsCrashLoop                     *bool                             `json:"isCrashLoop,omitempty"`
	RestartCount                    *int                              `json:"restartCount,omitempty"`
	RunningStartedTime              *string                           `json:"runningStartedTime,omitempty"`
	WaitingReasonEnum               *string                           `json:"waitingReasonEnum,omitempty"`
	WaitingMessage                  *string                           `json:"waitingMessage,omitempty"`
	HealthStatus                    *DesiredConditionStatus           `json:"healthStatus"`
	Processes                       []*K8sWorkloadPodContainerProcess `json:"processes"`
}

type K8sWorkloadPodContainerProcess struct {
	Healthy               *bool                                            `json:"healthy,omitempty"`
	HealthStatus          *DesiredConditionStatus                          `json:"healthStatus"`
	IdentifyingAttributes []*K8sWorkloadPodContainerProcessAttribute       `json:"identifyingAttributes"`
	Instrumentations      []*K8sWorkloadPodContainerProcessInstrumentation `json:"instrumentations,omitempty"`
}

type K8sWorkloadPodContainerProcessAttribute struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type K8sWorkloadPodContainerProcessInstrumentation struct {
	Name              string `json:"name"`
	IsStandardLibrary *bool  `json:"isStandardLibrary,omitempty"`
}

type K8sWorkloadRollout struct {
	RolloutStatus *DesiredConditionStatus `json:"rolloutStatus"`
}

type K8sWorkloadRuntimeInfo struct {
	Completed         bool                               `json:"completed"`
	CompletedStatus   *DesiredConditionStatus            `json:"completedStatus"`
	DetectedLanguages []ProgrammingLanguage              `json:"detectedLanguages,omitempty"`
	Containers        []*K8sWorkloadRuntimeInfoContainer `json:"containers,omitempty"`
}

type K8sWorkloadRuntimeInfoContainer struct {
	ContainerName           string              `json:"containerName"`
	Language                ProgrammingLanguage `json:"language"`
	RuntimeVersion          *string             `json:"runtimeVersion,omitempty"`
	ProcessEnvVars          []*EnvVar           `json:"processEnvVars"`
	ContainerRuntimeEnvVars []*EnvVar           `json:"containerRuntimeEnvVars,omitempty"`
	CriErrorMessage         *string             `json:"criErrorMessage,omitempty"`
	LibcType                *string             `json:"libcType,omitempty"`
	SecureExecutionMode     *bool               `json:"secureExecutionMode,omitempty"`
	OtherAgentName          *string             `json:"otherAgentName,omitempty"`
}

type K8sWorkloadTelemetryMetrics struct {
	TotalDataSentBytes *int                                                 `json:"totalDataSentBytes,omitempty"`
	ThroughputBytes    *int                                                 `json:"throughputBytes,omitempty"`
	ExpectingTelemetry *K8sWorkloadTelemetryMetricsExpectingTelemetryStatus `json:"expectingTelemetry"`
}

type K8sWorkloadTelemetryMetricsExpectingTelemetryStatus struct {
	IsExpectingTelemetry    *bool                   `json:"isExpectingTelemetry,omitempty"`
	TelemetryObservedStatus *DesiredConditionStatus `json:"telemetryObservedStatus"`
}

type LanguageConfig struct {
	Enabled bool    `json:"enabled"`
	EnvVars *string `json:"envVars,omitempty"`
}

type MessagingPayloadCollection struct {
	MaxPayloadLength    *int  `json:"maxPayloadLength,omitempty"`
	DropPartialPayloads *bool `json:"dropPartialPayloads,omitempty"`
}

type MessagingPayloadCollectionInput struct {
	MaxPayloadLength    *int  `json:"maxPayloadLength,omitempty"`
	DropPartialPayloads *bool `json:"dropPartialPayloads,omitempty"`
}

type MetricsSourceAgentJavaRuntimeMetricsConfig struct {
	Disabled *bool                                    `json:"disabled,omitempty"`
	Metrics  []*MetricsSourceAgentRuntimeMetricConfig `json:"metrics,omitempty"`
}

type MetricsSourceAgentMetricsConfig struct {
	SpanMetrics    *MetricsSourceAgentSpanMetricsConfig    `json:"spanMetrics,omitempty"`
	RuntimeMetrics *MetricsSourceAgentRuntimeMetricsConfig `json:"runtimeMetrics,omitempty"`
}

type MetricsSourceAgentRuntimeMetricConfig struct {
	Name     string `json:"name"`
	Disabled *bool  `json:"disabled,omitempty"`
}

type MetricsSourceAgentRuntimeMetricsConfig struct {
	Java *MetricsSourceAgentJavaRuntimeMetricsConfig `json:"java,omitempty"`
}

type MetricsSourceAgentSpanMetricsConfig struct {
	Enabled bool `json:"enabled"`
}

type MetricsSourceConfig struct {
	SpanMetrics      *MetricsSourceSpanMetricsConfig      `json:"spanMetrics,omitempty"`
	HostMetrics      *MetricsSourceHostMetricsConfig      `json:"hostMetrics,omitempty"`
	KubeletStats     *MetricsSourceKubeletStatsConfig     `json:"kubeletStats,omitempty"`
	OdigosOwnMetrics *MetricsSourceOdigosOwnMetricsConfig `json:"odigosOwnMetrics,omitempty"`
	AgentMetrics     *MetricsSourceAgentMetricsConfig     `json:"agentMetrics,omitempty"`
}

type MetricsSourceHostMetricsConfig struct {
	Disabled *bool   `json:"disabled,omitempty"`
	Interval *string `json:"interval,omitempty"`
}

type MetricsSourceKubeletStatsConfig struct {
	Disabled *bool   `json:"disabled,omitempty"`
	Interval *string `json:"interval,omitempty"`
}

type MetricsSourceOdigosOwnMetricsConfig struct {
	Interval *string `json:"interval,omitempty"`
}

type MetricsSourceSpanMetricsConfig struct {
	Disabled                     *bool    `json:"disabled,omitempty"`
	Interval                     *string  `json:"interval,omitempty"`
	MetricsExpiration            *string  `json:"metricsExpiration,omitempty"`
	AdditionalDimensions         []string `json:"additionalDimensions,omitempty"`
	HistogramDisabled            *bool    `json:"histogramDisabled,omitempty"`
	HistogramBuckets             []string `json:"histogramBuckets,omitempty"`
	IncludedProcessInDimensions  *bool    `json:"includedProcessInDimensions,omitempty"`
	ExcludedResourceAttributes   []string `json:"excludedResourceAttributes,omitempty"`
	ResourceMetricsKeyAttributes []string `json:"resourceMetricsKeyAttributes,omitempty"`
}

type Mutation struct {
}

type NodeCollectorAnalyze struct {
	Enabled        *EntityProperty `json:"enabled"`
	CollectorGroup *EntityProperty `json:"collectorGroup"`
	Deployed       *EntityProperty `json:"deployed,omitempty"`
	DeployedError  *EntityProperty `json:"deployedError,omitempty"`
	CollectorReady *EntityProperty `json:"collectorReady,omitempty"`
	DaemonSet      *EntityProperty `json:"daemonSet"`
	DesiredNodes   *EntityProperty `json:"desiredNodes,omitempty"`
	CurrentNodes   *EntityProperty `json:"currentNodes,omitempty"`
	UpdatedNodes   *EntityProperty `json:"updatedNodes,omitempty"`
	AvailableNodes *EntityProperty `json:"availableNodes,omitempty"`
}

type NodesSummary struct {
	Desired int `json:"desired"`
	Ready   int `json:"ready"`
}

type NonIdentifyingAttribute struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type NumberCondition struct {
	Operation     NumberOperation `json:"operation"`
	ExpectedValue float64         `json:"expectedValue"`
}

type NumberConditionInput struct {
	Operation     NumberOperation `json:"operation"`
	ExpectedValue float64         `json:"expectedValue"`
}

type ObservabilitySignalSupport struct {
	Supported bool `json:"supported"`
}

type OdigosAnalyze struct {
	OdigosVersion        *EntityProperty          `json:"odigosVersion"`
	KubernetesVersion    *EntityProperty          `json:"kubernetesVersion"`
	Tier                 *EntityProperty          `json:"tier"`
	InstallationMethod   *EntityProperty          `json:"installationMethod"`
	NumberOfDestinations int                      `json:"numberOfDestinations"`
	NumberOfSources      int                      `json:"numberOfSources"`
	ClusterCollector     *ClusterCollectorAnalyze `json:"clusterCollector"`
	NodeCollector        *NodeCollectorAnalyze    `json:"nodeCollector"`
	IsSettled            bool                     `json:"isSettled"`
	HasErrors            bool                     `json:"hasErrors"`
}

type OdigosOwnTelemetryConfig struct {
	MetricsStoreDisabled *bool `json:"metricsStoreDisabled,omitempty"`
}

type OidcConfig struct {
	TenantURL    *string `json:"tenantUrl,omitempty"`
	ClientID     *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
}

type OtelAgentsAnalyze struct {
	Created    *EntityProperty                `json:"created"`
	CreateTime *EntityProperty                `json:"createTime,omitempty"`
	Containers []*ContainerAgentConfigAnalyze `json:"containers"`
}

type OtlpExporterConfig struct {
	EnableDataCompression *bool                 `json:"enableDataCompression,omitempty"`
	Timeout               *string               `json:"timeout,omitempty"`
	RetryOnFailure        *RetryOnFailureConfig `json:"retryOnFailure,omitempty"`
}

type OverviewMetricsResponse struct {
	Sources      []*SingleSourceMetricsResponse      `json:"sources"`
	Destinations []*SingleDestinationMetricsResponse `json:"destinations"`
}

type PatchSourceRequestInput struct {
	CurrentStreamName string  `json:"currentStreamName"`
	OtelServiceName   *string `json:"otelServiceName,omitempty"`
	ContainerName     *string `json:"containerName,omitempty"`
	Language          *string `json:"language,omitempty"`
	Version           *string `json:"version,omitempty"`
	OtelDistroName    *string `json:"otelDistroName,omitempty"`
}

type PayloadCollection struct {
	HTTPRequest  *HTTPPayloadCollection      `json:"httpRequest,omitempty"`
	HTTPResponse *HTTPPayloadCollection      `json:"httpResponse,omitempty"`
	DbQuery      *DbQueryPayloadCollection   `json:"dbQuery,omitempty"`
	Messaging    *MessagingPayloadCollection `json:"messaging,omitempty"`
}

type PayloadCollectionInput struct {
	HTTPRequest  *HTTPPayloadCollectionInput      `json:"httpRequest,omitempty"`
	HTTPResponse *HTTPPayloadCollectionInput      `json:"httpResponse,omitempty"`
	DbQuery      *DbQueryPayloadCollectionInput   `json:"dbQuery,omitempty"`
	Messaging    *MessagingPayloadCollectionInput `json:"messaging,omitempty"`
}

type PersistNamespaceItemInput struct {
	Namespace         string `json:"namespace"`
	Selected          bool   `json:"selected"`
	CurrentStreamName string `json:"currentStreamName"`
}

type PersistNamespaceSourceInput struct {
	Namespace         string          `json:"namespace"`
	Name              string          `json:"name"`
	Kind              K8sResourceKind `json:"kind"`
	Selected          bool            `json:"selected"`
	CurrentStreamName string          `json:"currentStreamName"`
}

type PodAnalyze struct {
	PodName                       *EntityProperty        `json:"podName"`
	NodeName                      *EntityProperty        `json:"nodeName"`
	Phase                         *EntityProperty        `json:"phase"`
	AgentInjected                 *EntityProperty        `json:"agentInjected"`
	RunningLatestWorkloadRevision *EntityProperty        `json:"runningLatestWorkloadRevision,omitempty"`
	Containers                    []*PodContainerAnalyze `json:"containers"`
	ManifestYaml                  *string                `json:"manifestYAML,omitempty"`
}

type PodCondition struct {
	Type               *PodConditionType   `json:"type,omitempty"`
	Status             *K8sConditionStatus `json:"status,omitempty"`
	LastTransitionTime *string             `json:"lastTransitionTime,omitempty"`
	Reason             *string             `json:"reason,omitempty"`
	Message            *string             `json:"message,omitempty"`
}

type PodContainerAnalyze struct {
	ContainerName            *EntityProperty                   `json:"containerName"`
	ActualDevices            *EntityProperty                   `json:"actualDevices"`
	Started                  *EntityProperty                   `json:"started,omitempty"`
	Ready                    *EntityProperty                   `json:"ready,omitempty"`
	InstrumentationInstances []*InstrumentationInstanceAnalyze `json:"instrumentationInstances"`
}

type PodDetails struct {
	Name         string               `json:"name"`
	Namespace    string               `json:"namespace"`
	Node         *string              `json:"node,omitempty"`
	Status       *PodPhase            `json:"status,omitempty"`
	Containers   []*ContainerOverview `json:"containers"`
	ManifestYaml string               `json:"manifestYAML"`
}

type PodInfo struct {
	Namespace         string               `json:"namespace"`
	Name              string               `json:"name"`
	Status            string               `json:"status"`
	RestartsCount     int                  `json:"restartsCount"`
	NodeName          string               `json:"nodeName"`
	CreationTimestamp string               `json:"creationTimestamp"`
	Image             string               `json:"image"`
	CollectorMetrics  *CollectorPodMetrics `json:"collectorMetrics,omitempty"`
}

type PodWorkload struct {
	Namespace string          `json:"namespace"`
	Name      string          `json:"name"`
	Kind      K8sResourceKind `json:"kind"`
}

type PodWorkloadInput struct {
	Namespace string          `json:"namespace"`
	Kind      K8sResourceKind `json:"kind"`
	Name      string          `json:"name"`
}

type Query struct {
}

type RemoteConfig struct {
	Rollout *RemoteConfigRollout `json:"rollout,omitempty"`
}

type RemoteConfigInput struct {
	Rollout *RemoteConfigRolloutInput `json:"rollout,omitempty"`
}

type RemoteConfigRollout struct {
	AutomaticRolloutDisabled *bool `json:"automaticRolloutDisabled,omitempty"`
}

type RemoteConfigRolloutInput struct {
	AutomaticRolloutDisabled *bool `json:"automaticRolloutDisabled,omitempty"`
}

type ResourceAmounts struct {
	CPU    *string `json:"cpu,omitempty"`
	Memory *string `json:"memory,omitempty"`
}

type Resources struct {
	Requests *ResourceAmounts `json:"requests,omitempty"`
	Limits   *ResourceAmounts `json:"limits,omitempty"`
}

type RetryOnFailureConfig struct {
	Enabled         *bool   `json:"enabled,omitempty"`
	InitialInterval *string `json:"initialInterval,omitempty"`
	MaxInterval     *string `json:"maxInterval,omitempty"`
	MaxElapsedTime  *string `json:"maxElapsedTime,omitempty"`
}

type RolloutConfig struct {
	AutomaticRolloutDisabled *bool `json:"automaticRolloutDisabled,omitempty"`
}

type RuntimeInfoAnalyze struct {
	Generation *EntityProperty                `json:"generation"`
	Containers []*ContainerRuntimeInfoAnalyze `json:"containers"`
}

type Sampling struct {
	Configs *SamplingConfigs `json:"configs"`
}

type SamplingConfig struct {
	TailSampling            *TailSamplingConfig            `json:"tailSampling,omitempty"`
	K8sHealthProbesSampling *K8sHealthProbesSamplingConfig `json:"k8sHealthProbesSampling,omitempty"`
}

type SamplingConfigInput struct {
	TailSampling            *TailSamplingConfigInput            `json:"tailSampling,omitempty"`
	K8sHealthProbesSampling *K8sHealthProbesSamplingConfigInput `json:"k8sHealthProbesSampling,omitempty"`
}

type SamplingConfigs struct {
	Effective               *SamplingConfig `json:"effective,omitempty"`
	HelmDeployment          *SamplingConfig `json:"helmDeployment,omitempty"`
	RemoteConfigFromCentral *SamplingConfig `json:"remoteConfigFromCentral,omitempty"`
	LocalUIConfig           *SamplingConfig `json:"localUiConfig,omitempty"`
}

type ServiceMap struct {
	Services []*ServiceMapFromSource `json:"services"`
}

type ServiceMapFromSource struct {
	ServiceName string                `json:"serviceName"`
	Services    []*ServiceMapToSource `json:"services"`
}

type ServiceMapToSource struct {
	ServiceName string `json:"serviceName"`
	Requests    int    `json:"requests"`
	DateTime    string `json:"dateTime"`
}

type ServiceNameFilter struct {
	ServiceName           string  `json:"serviceName"`
	SamplingRatio         float64 `json:"samplingRatio"`
	FallbackSamplingRatio float64 `json:"fallbackSamplingRatio"`
}

type ServiceNameFilterInput struct {
	ServiceName           string  `json:"serviceName"`
	SamplingRatio         float64 `json:"samplingRatio"`
	FallbackSamplingRatio float64 `json:"fallbackSamplingRatio"`
}

type SingleDestinationMetricsResponse struct {
	ID            string `json:"id"`
	TotalDataSent int    `json:"totalDataSent"`
	Throughput    int    `json:"throughput"`
}

type SingleSourceMetricsResponse struct {
	Namespace     string `json:"namespace"`
	Kind          string `json:"kind"`
	Name          string `json:"name"`
	TotalDataSent int    `json:"totalDataSent"`
	Throughput    int    `json:"throughput"`
}

type SourceAnalyze struct {
	Name            *EntityProperty                `json:"name"`
	Kind            *EntityProperty                `json:"kind"`
	Namespace       *EntityProperty                `json:"namespace"`
	SourceObjects   *InstrumentationSourcesAnalyze `json:"sourceObjects"`
	RuntimeInfo     *RuntimeInfoAnalyze            `json:"runtimeInfo"`
	OtelAgents      *OtelAgentsAnalyze             `json:"otelAgents"`
	TotalPods       int                            `json:"totalPods"`
	PodsPhasesCount string                         `json:"podsPhasesCount"`
	Pods            []*PodAnalyze                  `json:"pods"`
}

type SourceConditions struct {
	Namespace  string          `json:"namespace"`
	Name       string          `json:"name"`
	Kind       K8sResourceKind `json:"kind"`
	Conditions []*Condition    `json:"conditions"`
}

type SourceContainer struct {
	ContainerName          string  `json:"containerName"`
	Language               string  `json:"language"`
	RuntimeVersion         string  `json:"runtimeVersion"`
	Overriden              bool    `json:"overriden"`
	Instrumented           bool    `json:"instrumented"`
	InstrumentationMessage string  `json:"instrumentationMessage"`
	OtelDistroName         *string `json:"otelDistroName,omitempty"`
}

type SpanAttributeFilter struct {
	ServiceName           string                     `json:"serviceName"`
	AttributeKey          string                     `json:"attributeKey"`
	Condition             *AttributeFiltersCondition `json:"condition"`
	SamplingRatio         float64                    `json:"samplingRatio"`
	FallbackSamplingRatio float64                    `json:"fallbackSamplingRatio"`
}

type SpanAttributeFilterInput struct {
	ServiceName           string                          `json:"serviceName"`
	AttributeKey          string                          `json:"attributeKey"`
	FallbackSamplingRatio float64                         `json:"fallbackSamplingRatio"`
	Condition             *AttributeFiltersConditionInput `json:"condition"`
}

type StringCondition struct {
	Operation     StringOperation `json:"operation"`
	ExpectedValue *string         `json:"expectedValue,omitempty"`
}

type StringConditionInput struct {
	Operation     StringOperation `json:"operation"`
	ExpectedValue *string         `json:"expectedValue,omitempty"`
}

type SupportedSignals struct {
	Traces  *ObservabilitySignalSupport `json:"traces"`
	Metrics *ObservabilitySignalSupport `json:"metrics"`
	Logs    *ObservabilitySignalSupport `json:"logs"`
}

type TailSamplingConfig struct {
	Disabled                     *bool   `json:"disabled,omitempty"`
	TraceAggregationWaitDuration *string `json:"traceAggregationWaitDuration,omitempty"`
}

type TailSamplingConfigInput struct {
	Disabled                     *bool   `json:"disabled,omitempty"`
	TraceAggregationWaitDuration *string `json:"traceAggregationWaitDuration,omitempty"`
}

type TestConnectionResponse struct {
	Succeeded       bool    `json:"succeeded"`
	StatusCode      int     `json:"statusCode"`
	DestinationType *string `json:"destinationType,omitempty"`
	Message         *string `json:"message,omitempty"`
	Reason          *string `json:"reason,omitempty"`
}

type UserInstrumentationEnvsConfig struct {
	Languages *string `json:"languages,omitempty"`
}

type WorkloadFilter struct {
	Namespace                *string          `json:"namespace,omitempty"`
	Kind                     *K8sResourceKind `json:"kind,omitempty"`
	Name                     *string          `json:"name,omitempty"`
	MarkedForInstrumentation *bool            `json:"markedForInstrumentation,omitempty"`
}

type ActionType string

const (
	ActionTypeK8sAttributesResolver ActionType = "K8sAttributesResolver"
	ActionTypeAddClusterInfo        ActionType = "AddClusterInfo"
	ActionTypeDeleteAttribute       ActionType = "DeleteAttribute"
	ActionTypeRenameAttribute       ActionType = "RenameAttribute"
	ActionTypePiiMasking            ActionType = "PiiMasking"
	ActionTypeErrorSampler          ActionType = "ErrorSampler"
	ActionTypeProbabilisticSampler  ActionType = "ProbabilisticSampler"
	ActionTypeLatencySampler        ActionType = "LatencySampler"
	ActionTypeServiceNameSampler    ActionType = "ServiceNameSampler"
	ActionTypeSpanAttributeSampler  ActionType = "SpanAttributeSampler"
	ActionTypeUnknownType           ActionType = "UnknownType"
)

var AllActionType = []ActionType{
	ActionTypeK8sAttributesResolver,
	ActionTypeAddClusterInfo,
	ActionTypeDeleteAttribute,
	ActionTypeRenameAttribute,
	ActionTypePiiMasking,
	ActionTypeErrorSampler,
	ActionTypeProbabilisticSampler,
	ActionTypeLatencySampler,
	ActionTypeServiceNameSampler,
	ActionTypeSpanAttributeSampler,
	ActionTypeUnknownType,
}

func (e ActionType) IsValid() bool {
	switch e {
	case ActionTypeK8sAttributesResolver, ActionTypeAddClusterInfo, ActionTypeDeleteAttribute, ActionTypeRenameAttribute, ActionTypePiiMasking, ActionTypeErrorSampler, ActionTypeProbabilisticSampler, ActionTypeLatencySampler, ActionTypeServiceNameSampler, ActionTypeSpanAttributeSampler, ActionTypeUnknownType:
		return true
	}
	return false
}

func (e ActionType) String() string {
	return string(e)
}

func (e *ActionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActionType", str)
	}
	return nil
}

func (e ActionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BooleanOperation string

const (
	BooleanOperationExists BooleanOperation = "exists"
	BooleanOperationEquals BooleanOperation = "equals"
)

var AllBooleanOperation = []BooleanOperation{
	BooleanOperationExists,
	BooleanOperationEquals,
}

func (e BooleanOperation) IsValid() bool {
	switch e {
	case BooleanOperationExists, BooleanOperationEquals:
		return true
	}
	return false
}

func (e BooleanOperation) String() string {
	return string(e)
}

func (e *BooleanOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BooleanOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BooleanOperation", str)
	}
	return nil
}

func (e BooleanOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ComputePlatformType string

const (
	ComputePlatformTypeK8s ComputePlatformType = "K8S"
	ComputePlatformTypeVM  ComputePlatformType = "VM"
)

var AllComputePlatformType = []ComputePlatformType{
	ComputePlatformTypeK8s,
	ComputePlatformTypeVM,
}

func (e ComputePlatformType) IsValid() bool {
	switch e {
	case ComputePlatformTypeK8s, ComputePlatformTypeVM:
		return true
	}
	return false
}

func (e ComputePlatformType) String() string {
	return string(e)
}

func (e *ComputePlatformType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ComputePlatformType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ComputePlatformType", str)
	}
	return nil
}

func (e ComputePlatformType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ConditionStatus string

const (
	ConditionStatusSuccess  ConditionStatus = "success"
	ConditionStatusError    ConditionStatus = "error"
	ConditionStatusDisabled ConditionStatus = "disabled"
	ConditionStatusLoading  ConditionStatus = "loading"
)

var AllConditionStatus = []ConditionStatus{
	ConditionStatusSuccess,
	ConditionStatusError,
	ConditionStatusDisabled,
	ConditionStatusLoading,
}

func (e ConditionStatus) IsValid() bool {
	switch e {
	case ConditionStatusSuccess, ConditionStatusError, ConditionStatusDisabled, ConditionStatusLoading:
		return true
	}
	return false
}

func (e ConditionStatus) String() string {
	return string(e)
}

func (e *ConditionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConditionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConditionStatus", str)
	}
	return nil
}

func (e ConditionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ContainerLifecycleStatus string

const (
	ContainerLifecycleStatusRunning    ContainerLifecycleStatus = "Running"
	ContainerLifecycleStatusWaiting    ContainerLifecycleStatus = "Waiting"
	ContainerLifecycleStatusTerminated ContainerLifecycleStatus = "Terminated"
)

var AllContainerLifecycleStatus = []ContainerLifecycleStatus{
	ContainerLifecycleStatusRunning,
	ContainerLifecycleStatusWaiting,
	ContainerLifecycleStatusTerminated,
}

func (e ContainerLifecycleStatus) IsValid() bool {
	switch e {
	case ContainerLifecycleStatusRunning, ContainerLifecycleStatusWaiting, ContainerLifecycleStatusTerminated:
		return true
	}
	return false
}

func (e ContainerLifecycleStatus) String() string {
	return string(e)
}

func (e *ContainerLifecycleStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContainerLifecycleStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContainerLifecycleStatus", str)
	}
	return nil
}

func (e ContainerLifecycleStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DesiredStateProgress string

const (
	DesiredStateProgressError       DesiredStateProgress = "Error"
	DesiredStateProgressFailure     DesiredStateProgress = "Failure"
	DesiredStateProgressNotice      DesiredStateProgress = "Notice"
	DesiredStateProgressPending     DesiredStateProgress = "Pending"
	DesiredStateProgressWaiting     DesiredStateProgress = "Waiting"
	DesiredStateProgressUnsupported DesiredStateProgress = "Unsupported"
	DesiredStateProgressDisabled    DesiredStateProgress = "Disabled"
	DesiredStateProgressSuccess     DesiredStateProgress = "Success"
	DesiredStateProgressIrrelevant  DesiredStateProgress = "Irrelevant"
	DesiredStateProgressUnknown     DesiredStateProgress = "Unknown"
)

var AllDesiredStateProgress = []DesiredStateProgress{
	DesiredStateProgressError,
	DesiredStateProgressFailure,
	DesiredStateProgressNotice,
	DesiredStateProgressPending,
	DesiredStateProgressWaiting,
	DesiredStateProgressUnsupported,
	DesiredStateProgressDisabled,
	DesiredStateProgressSuccess,
	DesiredStateProgressIrrelevant,
	DesiredStateProgressUnknown,
}

func (e DesiredStateProgress) IsValid() bool {
	switch e {
	case DesiredStateProgressError, DesiredStateProgressFailure, DesiredStateProgressNotice, DesiredStateProgressPending, DesiredStateProgressWaiting, DesiredStateProgressUnsupported, DesiredStateProgressDisabled, DesiredStateProgressSuccess, DesiredStateProgressIrrelevant, DesiredStateProgressUnknown:
		return true
	}
	return false
}

func (e DesiredStateProgress) String() string {
	return string(e)
}

func (e *DesiredStateProgress) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DesiredStateProgress(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DesiredStateProgress", str)
	}
	return nil
}

func (e DesiredStateProgress) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EnvInjectionMethod string

const (
	EnvInjectionMethodLoader                      EnvInjectionMethod = "loader"
	EnvInjectionMethodPodManifest                 EnvInjectionMethod = "pod_manifest"
	EnvInjectionMethodLoaderFallbackToPodManifest EnvInjectionMethod = "loader_fallback_to_pod_manifest"
)

var AllEnvInjectionMethod = []EnvInjectionMethod{
	EnvInjectionMethodLoader,
	EnvInjectionMethodPodManifest,
	EnvInjectionMethodLoaderFallbackToPodManifest,
}

func (e EnvInjectionMethod) IsValid() bool {
	switch e {
	case EnvInjectionMethodLoader, EnvInjectionMethodPodManifest, EnvInjectionMethodLoaderFallbackToPodManifest:
		return true
	}
	return false
}

func (e EnvInjectionMethod) String() string {
	return string(e)
}

func (e *EnvInjectionMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EnvInjectionMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EnvInjectionMethod", str)
	}
	return nil
}

func (e EnvInjectionMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type InstallationStatus string

const (
	InstallationStatusNew          InstallationStatus = "NEW"
	InstallationStatusAppsSelected InstallationStatus = "APPS_SELECTED"
	InstallationStatusFinished     InstallationStatus = "FINISHED"
)

var AllInstallationStatus = []InstallationStatus{
	InstallationStatusNew,
	InstallationStatusAppsSelected,
	InstallationStatusFinished,
}

func (e InstallationStatus) IsValid() bool {
	switch e {
	case InstallationStatusNew, InstallationStatusAppsSelected, InstallationStatusFinished:
		return true
	}
	return false
}

func (e InstallationStatus) String() string {
	return string(e)
}

func (e *InstallationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InstallationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InstallationStatus", str)
	}
	return nil
}

func (e InstallationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type InstrumentationRuleType string

const (
	InstrumentationRuleTypeCodeAttributes        InstrumentationRuleType = "CodeAttributes"
	InstrumentationRuleTypeHeadersCollection     InstrumentationRuleType = "HeadersCollection"
	InstrumentationRuleTypePayloadCollection     InstrumentationRuleType = "PayloadCollection"
	InstrumentationRuleTypeCustomInstrumentation InstrumentationRuleType = "CustomInstrumentation"
	InstrumentationRuleTypeUnknownType           InstrumentationRuleType = "UnknownType"
)

var AllInstrumentationRuleType = []InstrumentationRuleType{
	InstrumentationRuleTypeCodeAttributes,
	InstrumentationRuleTypeHeadersCollection,
	InstrumentationRuleTypePayloadCollection,
	InstrumentationRuleTypeCustomInstrumentation,
	InstrumentationRuleTypeUnknownType,
}

func (e InstrumentationRuleType) IsValid() bool {
	switch e {
	case InstrumentationRuleTypeCodeAttributes, InstrumentationRuleTypeHeadersCollection, InstrumentationRuleTypePayloadCollection, InstrumentationRuleTypeCustomInstrumentation, InstrumentationRuleTypeUnknownType:
		return true
	}
	return false
}

func (e InstrumentationRuleType) String() string {
	return string(e)
}

func (e *InstrumentationRuleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InstrumentationRuleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InstrumentationRuleType", str)
	}
	return nil
}

func (e InstrumentationRuleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type JSONOperation string

const (
	JSONOperationExists         JSONOperation = "exists"
	JSONOperationEquals         JSONOperation = "equals"
	JSONOperationNotEquals      JSONOperation = "not_equals"
	JSONOperationIsValidJSON    JSONOperation = "is_valid_json"
	JSONOperationIsInvalidJSON  JSONOperation = "is_invalid_json"
	JSONOperationJsonpathExists JSONOperation = "jsonpath_exists"
	JSONOperationKeyEquals      JSONOperation = "key_equals"
	JSONOperationKeyNotEquals   JSONOperation = "key_not_equals"
)

var AllJSONOperation = []JSONOperation{
	JSONOperationExists,
	JSONOperationEquals,
	JSONOperationNotEquals,
	JSONOperationIsValidJSON,
	JSONOperationIsInvalidJSON,
	JSONOperationJsonpathExists,
	JSONOperationKeyEquals,
	JSONOperationKeyNotEquals,
}

func (e JSONOperation) IsValid() bool {
	switch e {
	case JSONOperationExists, JSONOperationEquals, JSONOperationNotEquals, JSONOperationIsValidJSON, JSONOperationIsInvalidJSON, JSONOperationJsonpathExists, JSONOperationKeyEquals, JSONOperationKeyNotEquals:
		return true
	}
	return false
}

func (e JSONOperation) String() string {
	return string(e)
}

func (e *JSONOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JSONOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JsonOperation", str)
	}
	return nil
}

func (e JSONOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type K8sAttributesFrom string

const (
	K8sAttributesFromPod       K8sAttributesFrom = "pod"
	K8sAttributesFromNamespace K8sAttributesFrom = "namespace"
	K8sAttributesFromNode      K8sAttributesFrom = "node"
)

var AllK8sAttributesFrom = []K8sAttributesFrom{
	K8sAttributesFromPod,
	K8sAttributesFromNamespace,
	K8sAttributesFromNode,
}

func (e K8sAttributesFrom) IsValid() bool {
	switch e {
	case K8sAttributesFromPod, K8sAttributesFromNamespace, K8sAttributesFromNode:
		return true
	}
	return false
}

func (e K8sAttributesFrom) String() string {
	return string(e)
}

func (e *K8sAttributesFrom) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = K8sAttributesFrom(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid K8sAttributesFrom", str)
	}
	return nil
}

func (e K8sAttributesFrom) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type K8sConditionStatus string

const (
	K8sConditionStatusTrue    K8sConditionStatus = "True"
	K8sConditionStatusFalse   K8sConditionStatus = "False"
	K8sConditionStatusUnknown K8sConditionStatus = "Unknown"
)

var AllK8sConditionStatus = []K8sConditionStatus{
	K8sConditionStatusTrue,
	K8sConditionStatusFalse,
	K8sConditionStatusUnknown,
}

func (e K8sConditionStatus) IsValid() bool {
	switch e {
	case K8sConditionStatusTrue, K8sConditionStatusFalse, K8sConditionStatusUnknown:
		return true
	}
	return false
}

func (e K8sConditionStatus) String() string {
	return string(e)
}

func (e *K8sConditionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = K8sConditionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid K8sConditionStatus", str)
	}
	return nil
}

func (e K8sConditionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type K8sResourceKind string

const (
	K8sResourceKindDeployment            K8sResourceKind = "Deployment"
	K8sResourceKindDaemonSet             K8sResourceKind = "DaemonSet"
	K8sResourceKindStatefulSet           K8sResourceKind = "StatefulSet"
	K8sResourceKindCronJob               K8sResourceKind = "CronJob"
	K8sResourceKindConfigMap             K8sResourceKind = "ConfigMap"
	K8sResourceKindPod                   K8sResourceKind = "Pod"
	K8sResourceKindStaticPod             K8sResourceKind = "StaticPod"
	K8sResourceKindDeploymentConfig      K8sResourceKind = "DeploymentConfig"
	K8sResourceKindRollout               K8sResourceKind = "Rollout"
	K8sResourceKindInstrumentationConfig K8sResourceKind = "InstrumentationConfig"
)

var AllK8sResourceKind = []K8sResourceKind{
	K8sResourceKindDeployment,
	K8sResourceKindDaemonSet,
	K8sResourceKindStatefulSet,
	K8sResourceKindCronJob,
	K8sResourceKindConfigMap,
	K8sResourceKindPod,
	K8sResourceKindStaticPod,
	K8sResourceKindDeploymentConfig,
	K8sResourceKindRollout,
	K8sResourceKindInstrumentationConfig,
}

func (e K8sResourceKind) IsValid() bool {
	switch e {
	case K8sResourceKindDeployment, K8sResourceKindDaemonSet, K8sResourceKindStatefulSet, K8sResourceKindCronJob, K8sResourceKindConfigMap, K8sResourceKindPod, K8sResourceKindStaticPod, K8sResourceKindDeploymentConfig, K8sResourceKindRollout, K8sResourceKindInstrumentationConfig:
		return true
	}
	return false
}

func (e K8sResourceKind) String() string {
	return string(e)
}

func (e *K8sResourceKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = K8sResourceKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid K8sResourceKind", str)
	}
	return nil
}

func (e K8sResourceKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator string

const (
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorEquals    K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator = "equals"
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorNotEquals K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator = "notEquals"
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorEndWith   K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator = "endWith"
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorStartWith K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator = "startWith"
)

var AllK8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator = []K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator{
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorEquals,
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorNotEquals,
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorEndWith,
	K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorStartWith,
}

func (e K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator) IsValid() bool {
	switch e {
	case K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorEquals, K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorNotEquals, K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorEndWith, K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperatorStartWith:
		return true
	}
	return false
}

func (e K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator) String() string {
	return string(e)
}

func (e *K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator", str)
	}
	return nil
}

func (e K8sWorkloadContainerAgentConfigTracesHeadSamplingCheckConditionOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ManifestFormat string

const (
	ManifestFormatYaml ManifestFormat = "YAML"
	ManifestFormatJSON ManifestFormat = "JSON"
)

var AllManifestFormat = []ManifestFormat{
	ManifestFormatYaml,
	ManifestFormatJSON,
}

func (e ManifestFormat) IsValid() bool {
	switch e {
	case ManifestFormatYaml, ManifestFormatJSON:
		return true
	}
	return false
}

func (e ManifestFormat) String() string {
	return string(e)
}

func (e *ManifestFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ManifestFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ManifestFormat", str)
	}
	return nil
}

func (e ManifestFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MountMethod string

const (
	MountMethodK8sVirtualDevice MountMethod = "k8s_virtual_device"
	MountMethodK8sHostPath      MountMethod = "k8s_host_path"
	MountMethodK8sInitContainer MountMethod = "k8s_init_container"
)

var AllMountMethod = []MountMethod{
	MountMethodK8sVirtualDevice,
	MountMethodK8sHostPath,
	MountMethodK8sInitContainer,
}

func (e MountMethod) IsValid() bool {
	switch e {
	case MountMethodK8sVirtualDevice, MountMethodK8sHostPath, MountMethodK8sInitContainer:
		return true
	}
	return false
}

func (e MountMethod) String() string {
	return string(e)
}

func (e *MountMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MountMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MountMethod", str)
	}
	return nil
}

func (e MountMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type NumberOperation string

const (
	NumberOperationExists             NumberOperation = "exists"
	NumberOperationEquals             NumberOperation = "equals"
	NumberOperationNotEquals          NumberOperation = "not_equals"
	NumberOperationGreaterThan        NumberOperation = "greater_than"
	NumberOperationLessThan           NumberOperation = "less_than"
	NumberOperationGreaterThanOrEqual NumberOperation = "greater_than_or_equal"
	NumberOperationLessThanOrEqual    NumberOperation = "less_than_or_equal"
)

var AllNumberOperation = []NumberOperation{
	NumberOperationExists,
	NumberOperationEquals,
	NumberOperationNotEquals,
	NumberOperationGreaterThan,
	NumberOperationLessThan,
	NumberOperationGreaterThanOrEqual,
	NumberOperationLessThanOrEqual,
}

func (e NumberOperation) IsValid() bool {
	switch e {
	case NumberOperationExists, NumberOperationEquals, NumberOperationNotEquals, NumberOperationGreaterThan, NumberOperationLessThan, NumberOperationGreaterThanOrEqual, NumberOperationLessThanOrEqual:
		return true
	}
	return false
}

func (e NumberOperation) String() string {
	return string(e)
}

func (e *NumberOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NumberOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NumberOperation", str)
	}
	return nil
}

func (e NumberOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PodConditionType string

const (
	PodConditionTypePodScheduled    PodConditionType = "PodScheduled"
	PodConditionTypeInitialized     PodConditionType = "Initialized"
	PodConditionTypeContainersReady PodConditionType = "ContainersReady"
	PodConditionTypeReady           PodConditionType = "Ready"
	PodConditionTypeOther           PodConditionType = "Other"
)

var AllPodConditionType = []PodConditionType{
	PodConditionTypePodScheduled,
	PodConditionTypeInitialized,
	PodConditionTypeContainersReady,
	PodConditionTypeReady,
	PodConditionTypeOther,
}

func (e PodConditionType) IsValid() bool {
	switch e {
	case PodConditionTypePodScheduled, PodConditionTypeInitialized, PodConditionTypeContainersReady, PodConditionTypeReady, PodConditionTypeOther:
		return true
	}
	return false
}

func (e PodConditionType) String() string {
	return string(e)
}

func (e *PodConditionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PodConditionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PodConditionType", str)
	}
	return nil
}

func (e PodConditionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PodPhase string

const (
	PodPhasePending   PodPhase = "Pending"
	PodPhaseRunning   PodPhase = "Running"
	PodPhaseSucceeded PodPhase = "Succeeded"
	PodPhaseFailed    PodPhase = "Failed"
	PodPhaseUnknown   PodPhase = "Unknown"
)

var AllPodPhase = []PodPhase{
	PodPhasePending,
	PodPhaseRunning,
	PodPhaseSucceeded,
	PodPhaseFailed,
	PodPhaseUnknown,
}

func (e PodPhase) IsValid() bool {
	switch e {
	case PodPhasePending, PodPhaseRunning, PodPhaseSucceeded, PodPhaseFailed, PodPhaseUnknown:
		return true
	}
	return false
}

func (e PodPhase) String() string {
	return string(e)
}

func (e *PodPhase) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PodPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PodPhase", str)
	}
	return nil
}

func (e PodPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProgrammingLanguage string

const (
	ProgrammingLanguageUnspecified ProgrammingLanguage = "Unspecified"
	ProgrammingLanguageJava        ProgrammingLanguage = "Java"
	ProgrammingLanguageGo          ProgrammingLanguage = "Go"
	ProgrammingLanguageJavaScript  ProgrammingLanguage = "JavaScript"
	ProgrammingLanguagePython      ProgrammingLanguage = "Python"
	ProgrammingLanguageDotNet      ProgrammingLanguage = "DotNet"
)

var AllProgrammingLanguage = []ProgrammingLanguage{
	ProgrammingLanguageUnspecified,
	ProgrammingLanguageJava,
	ProgrammingLanguageGo,
	ProgrammingLanguageJavaScript,
	ProgrammingLanguagePython,
	ProgrammingLanguageDotNet,
}

func (e ProgrammingLanguage) IsValid() bool {
	switch e {
	case ProgrammingLanguageUnspecified, ProgrammingLanguageJava, ProgrammingLanguageGo, ProgrammingLanguageJavaScript, ProgrammingLanguagePython, ProgrammingLanguageDotNet:
		return true
	}
	return false
}

func (e ProgrammingLanguage) String() string {
	return string(e)
}

func (e *ProgrammingLanguage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgrammingLanguage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgrammingLanguage", str)
	}
	return nil
}

func (e ProgrammingLanguage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SignalType string

const (
	SignalTypeTraces  SignalType = "TRACES"
	SignalTypeMetrics SignalType = "METRICS"
	SignalTypeLogs    SignalType = "LOGS"
)

var AllSignalType = []SignalType{
	SignalTypeTraces,
	SignalTypeMetrics,
	SignalTypeLogs,
}

func (e SignalType) IsValid() bool {
	switch e {
	case SignalTypeTraces, SignalTypeMetrics, SignalTypeLogs:
		return true
	}
	return false
}

func (e SignalType) String() string {
	return string(e)
}

func (e *SignalType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SignalType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SignalType", str)
	}
	return nil
}

func (e SignalType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SpanKind string

const (
	SpanKindInternal SpanKind = "Internal"
	SpanKindServer   SpanKind = "Server"
	SpanKindClient   SpanKind = "Client"
	SpanKindProducer SpanKind = "Producer"
	SpanKindConsumer SpanKind = "Consumer"
)

var AllSpanKind = []SpanKind{
	SpanKindInternal,
	SpanKindServer,
	SpanKindClient,
	SpanKindProducer,
	SpanKindConsumer,
}

func (e SpanKind) IsValid() bool {
	switch e {
	case SpanKindInternal, SpanKindServer, SpanKindClient, SpanKindProducer, SpanKindConsumer:
		return true
	}
	return false
}

func (e SpanKind) String() string {
	return string(e)
}

func (e *SpanKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SpanKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SpanKind", str)
	}
	return nil
}

func (e SpanKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type StringOperation string

const (
	StringOperationExists      StringOperation = "exists"
	StringOperationEquals      StringOperation = "equals"
	StringOperationNotEquals   StringOperation = "not_equals"
	StringOperationContains    StringOperation = "contains"
	StringOperationNotContains StringOperation = "not_contains"
	StringOperationRegex       StringOperation = "regex"
)

var AllStringOperation = []StringOperation{
	StringOperationExists,
	StringOperationEquals,
	StringOperationNotEquals,
	StringOperationContains,
	StringOperationNotContains,
	StringOperationRegex,
}

func (e StringOperation) IsValid() bool {
	switch e {
	case StringOperationExists, StringOperationEquals, StringOperationNotEquals, StringOperationContains, StringOperationNotContains, StringOperationRegex:
		return true
	}
	return false
}

func (e StringOperation) String() string {
	return string(e)
}

func (e *StringOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StringOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StringOperation", str)
	}
	return nil
}

func (e StringOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Tier string

const (
	TierCommunity Tier = "community"
	TierCloud     Tier = "cloud"
	TierOnprem    Tier = "onprem"
)

var AllTier = []Tier{
	TierCommunity,
	TierCloud,
	TierOnprem,
}

func (e Tier) IsValid() bool {
	switch e {
	case TierCommunity, TierCloud, TierOnprem:
		return true
	}
	return false
}

func (e Tier) String() string {
	return string(e)
}

func (e *Tier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Tier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Tier", str)
	}
	return nil
}

func (e Tier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UIMode string

const (
	UIModeDefault  UIMode = "default"
	UIModeReadonly UIMode = "readonly"
)

var AllUIMode = []UIMode{
	UIModeDefault,
	UIModeReadonly,
}

func (e UIMode) IsValid() bool {
	switch e {
	case UIModeDefault, UIModeReadonly:
		return true
	}
	return false
}

func (e UIMode) String() string {
	return string(e)
}

func (e *UIMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UIMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UiMode", str)
	}
	return nil
}

func (e UIMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// Rollout/availability status of a workload.
//
// - Healthy: All desired replicas are updated, available, and ready.
// - Updating: Workload is progressing towards desired state (e.g., updating pods).
// - Degraded: Progressing but with availability issues (e.g., not enough available replicas).
// - Failed: Progress deadline exceeded or an unrecoverable error occurred.
// - Down: No available replicas.
// - Unknown: Status cannot be determined from current signals.
type WorkloadRolloutStatus string

const (
	WorkloadRolloutStatusHealthy  WorkloadRolloutStatus = "Healthy"
	WorkloadRolloutStatusUpdating WorkloadRolloutStatus = "Updating"
	WorkloadRolloutStatusDegraded WorkloadRolloutStatus = "Degraded"
	WorkloadRolloutStatusFailed   WorkloadRolloutStatus = "Failed"
	WorkloadRolloutStatusDown     WorkloadRolloutStatus = "Down"
	WorkloadRolloutStatusUnknown  WorkloadRolloutStatus = "Unknown"
)

var AllWorkloadRolloutStatus = []WorkloadRolloutStatus{
	WorkloadRolloutStatusHealthy,
	WorkloadRolloutStatusUpdating,
	WorkloadRolloutStatusDegraded,
	WorkloadRolloutStatusFailed,
	WorkloadRolloutStatusDown,
	WorkloadRolloutStatusUnknown,
}

func (e WorkloadRolloutStatus) IsValid() bool {
	switch e {
	case WorkloadRolloutStatusHealthy, WorkloadRolloutStatusUpdating, WorkloadRolloutStatusDegraded, WorkloadRolloutStatusFailed, WorkloadRolloutStatusDown, WorkloadRolloutStatusUnknown:
		return true
	}
	return false
}

func (e WorkloadRolloutStatus) String() string {
	return string(e)
}

func (e *WorkloadRolloutStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkloadRolloutStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkloadRolloutStatus", str)
	}
	return nil
}

func (e WorkloadRolloutStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
