# .github/actions/run-chaos-tests/action.yml

name: "Chaos Tests"
description: "Chaos tests entrypoint"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.2.12

    - name: Install k3d
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.9.0 bash

    - name: Create k3d Cluster
      shell: bash
      run: |
        k3d cluster create --config tests/common/apply/k3d-config.yaml \
          --image rancher/k3s:v1.32.0-k3s1

    - name: Build Odigos CLI
      uses: ./.github/actions/build/cli

    - name: Run Chaos Tests
      shell: bash
      run: |
        export COMMIT_HASH="${GITHUB_SHA}"
        chainsaw test tests/chaos/network-latency/leader-election
