# .github/actions/run-chaos-tests/action.yml

name: "Chaos Tests"
description: "Chaos tests entrypoint"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.2.12

    - name: Create k0s Cluster
      shell: bash
      env:
        K0S_IMAGE: docker.io/k0sproject/k0s:v1.32.13-k0s.0
      run: ./scripts/k0s-cluster.sh create

    - name: Build Odigos CLI
      uses: ./.github/actions/build/cli

    - name: Run Chaos Tests
      shell: bash
      run: |
        export COMMIT_HASH="${GITHUB_SHA}"
        chainsaw test tests/chaos/network-latency/leader-election
