{{- if ne .Values.goAutoOffsetsMode "off" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odigos-go-offsets-updater
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
{{- end }}
