package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/services"
)

// GetGatewayDeploymentInfo is the resolver for the getGatewayDeploymentInfo field.
func (r *queryResolver) GetGatewayDeploymentInfo(ctx context.Context) (*model.GatewayDeploymentInfo, error) {
	return services.GetGatewayDeploymentInfo(ctx)
}

// GetGatewayDeploymentManifest is the resolver for the getGatewayDeploymentManifest field.
func (r *queryResolver) GetGatewayDeploymentManifest(ctx context.Context, format *model.ManifestFormat) (string, error) {
	return services.GetGatewayDeploymentManifest(ctx, format)
}
