package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/services"
)

// InstrumentationAgents is the resolver for the instrumentationAgents field.
func (r *queryResolver) InstrumentationAgents(ctx context.Context) ([]*model.InstrumentationAgent, error) {
	return services.GetInstrumentationAgents(ctx, r.K8sCacheClient, r.DistrosProvider)
}
