package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/services/tracecorrelations"
)

// TraceCorrelations is the resolver for the traceCorrelations field.
func (r *queryResolver) TraceCorrelations(ctx context.Context, filter *model.WorkloadFilter, timeRange *model.TraceCorrelationsTimeRangeInput) (*model.TraceCorrelations, error) {
	enabled, err := tracecorrelations.IsEnabled(ctx, r.K8sCacheClient)
	if err != nil {
		return nil, err
	}
	if !enabled {
		return nil, tracecorrelations.ErrNotEnabled
	}
	return tracecorrelations.GetTraceCorrelations(ctx, r.CorrelationsPromAPI, r.CorrelationsMetricsStoreURL, filter, timeRange)
}
