apiVersion: v1
kind: ServiceAccount
metadata:
  name: odigos-ui
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
  {{- if and .Values.marketplace.enabled .Values.marketplace.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.marketplace.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
