//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/odigos-io/odigos/common"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddClusterInfo) DeepCopyInto(out *AddClusterInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterInfo.
func (in *AddClusterInfo) DeepCopy() *AddClusterInfo {
	if in == nil {
		return nil
	}
	out := new(AddClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AddClusterInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddClusterInfoConfig) DeepCopyInto(out *AddClusterInfoConfig) {
	*out = *in
	if in.ClusterAttributes != nil {
		in, out := &in.ClusterAttributes, &out.ClusterAttributes
		*out = make([]OtelAttributeWithValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterInfoConfig.
func (in *AddClusterInfoConfig) DeepCopy() *AddClusterInfoConfig {
	if in == nil {
		return nil
	}
	out := new(AddClusterInfoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddClusterInfoList) DeepCopyInto(out *AddClusterInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AddClusterInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterInfoList.
func (in *AddClusterInfoList) DeepCopy() *AddClusterInfoList {
	if in == nil {
		return nil
	}
	out := new(AddClusterInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AddClusterInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddClusterInfoSpec) DeepCopyInto(out *AddClusterInfoSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.ClusterAttributes != nil {
		in, out := &in.ClusterAttributes, &out.ClusterAttributes
		*out = make([]OtelAttributeWithValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterInfoSpec.
func (in *AddClusterInfoSpec) DeepCopy() *AddClusterInfoSpec {
	if in == nil {
		return nil
	}
	out := new(AddClusterInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddClusterInfoStatus) DeepCopyInto(out *AddClusterInfoStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterInfoStatus.
func (in *AddClusterInfoStatus) DeepCopy() *AddClusterInfoStatus {
	if in == nil {
		return nil
	}
	out := new(AddClusterInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeCondition) DeepCopyInto(out *AttributeCondition) {
	*out = *in
	if in.StringCondition != nil {
		in, out := &in.StringCondition, &out.StringCondition
		*out = new(StringAttributeCondition)
		**out = **in
	}
	if in.NumberCondition != nil {
		in, out := &in.NumberCondition, &out.NumberCondition
		*out = new(NumberAttributeCondition)
		**out = **in
	}
	if in.BooleanCondition != nil {
		in, out := &in.BooleanCondition, &out.BooleanCondition
		*out = new(BooleanAttributeCondition)
		**out = **in
	}
	if in.JsonCondition != nil {
		in, out := &in.JsonCondition, &out.JsonCondition
		*out = new(JsonAttributeCondition)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeCondition.
func (in *AttributeCondition) DeepCopy() *AttributeCondition {
	if in == nil {
		return nil
	}
	out := new(AttributeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BooleanAttributeCondition) DeepCopyInto(out *BooleanAttributeCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BooleanAttributeCondition.
func (in *BooleanAttributeCondition) DeepCopy() *BooleanAttributeCondition {
	if in == nil {
		return nil
	}
	out := new(BooleanAttributeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultSamplerConfig) DeepCopyInto(out *DefaultSamplerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultSamplerConfig.
func (in *DefaultSamplerConfig) DeepCopy() *DefaultSamplerConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultSamplerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAttribute) DeepCopyInto(out *DeleteAttribute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAttribute.
func (in *DeleteAttribute) DeepCopy() *DeleteAttribute {
	if in == nil {
		return nil
	}
	out := new(DeleteAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeleteAttribute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAttributeConfig) DeepCopyInto(out *DeleteAttributeConfig) {
	*out = *in
	if in.AttributeNamesToDelete != nil {
		in, out := &in.AttributeNamesToDelete, &out.AttributeNamesToDelete
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAttributeConfig.
func (in *DeleteAttributeConfig) DeepCopy() *DeleteAttributeConfig {
	if in == nil {
		return nil
	}
	out := new(DeleteAttributeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAttributeList) DeepCopyInto(out *DeleteAttributeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeleteAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAttributeList.
func (in *DeleteAttributeList) DeepCopy() *DeleteAttributeList {
	if in == nil {
		return nil
	}
	out := new(DeleteAttributeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeleteAttributeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAttributeSpec) DeepCopyInto(out *DeleteAttributeSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.AttributeNamesToDelete != nil {
		in, out := &in.AttributeNamesToDelete, &out.AttributeNamesToDelete
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAttributeSpec.
func (in *DeleteAttributeSpec) DeepCopy() *DeleteAttributeSpec {
	if in == nil {
		return nil
	}
	out := new(DeleteAttributeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAttributeStatus) DeepCopyInto(out *DeleteAttributeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAttributeStatus.
func (in *DeleteAttributeStatus) DeepCopy() *DeleteAttributeStatus {
	if in == nil {
		return nil
	}
	out := new(DeleteAttributeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorSampler) DeepCopyInto(out *ErrorSampler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorSampler.
func (in *ErrorSampler) DeepCopy() *ErrorSampler {
	if in == nil {
		return nil
	}
	out := new(ErrorSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ErrorSampler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorSamplerConfig) DeepCopyInto(out *ErrorSamplerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorSamplerConfig.
func (in *ErrorSamplerConfig) DeepCopy() *ErrorSamplerConfig {
	if in == nil {
		return nil
	}
	out := new(ErrorSamplerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorSamplerList) DeepCopyInto(out *ErrorSamplerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ErrorSampler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorSamplerList.
func (in *ErrorSamplerList) DeepCopy() *ErrorSamplerList {
	if in == nil {
		return nil
	}
	out := new(ErrorSamplerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ErrorSamplerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorSamplerSpec) DeepCopyInto(out *ErrorSamplerSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorSamplerSpec.
func (in *ErrorSamplerSpec) DeepCopy() *ErrorSamplerSpec {
	if in == nil {
		return nil
	}
	out := new(ErrorSamplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorSamplerStatus) DeepCopyInto(out *ErrorSamplerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorSamplerStatus.
func (in *ErrorSamplerStatus) DeepCopy() *ErrorSamplerStatus {
	if in == nil {
		return nil
	}
	out := new(ErrorSamplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpRouteFilter) DeepCopyInto(out *HttpRouteFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpRouteFilter.
func (in *HttpRouteFilter) DeepCopy() *HttpRouteFilter {
	if in == nil {
		return nil
	}
	out := new(HttpRouteFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnoreHealthChecksConfig) DeepCopyInto(out *IgnoreHealthChecksConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnoreHealthChecksConfig.
func (in *IgnoreHealthChecksConfig) DeepCopy() *IgnoreHealthChecksConfig {
	if in == nil {
		return nil
	}
	out := new(IgnoreHealthChecksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JsonAttributeCondition) DeepCopyInto(out *JsonAttributeCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JsonAttributeCondition.
func (in *JsonAttributeCondition) DeepCopy() *JsonAttributeCondition {
	if in == nil {
		return nil
	}
	out := new(JsonAttributeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAnnotationAttribute) DeepCopyInto(out *K8sAnnotationAttribute) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromSources != nil {
		in, out := &in.FromSources, &out.FromSources
		*out = make([]K8sAttributeSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAnnotationAttribute.
func (in *K8sAnnotationAttribute) DeepCopy() *K8sAnnotationAttribute {
	if in == nil {
		return nil
	}
	out := new(K8sAnnotationAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAttributesConfig) DeepCopyInto(out *K8sAttributesConfig) {
	*out = *in
	if in.LabelsAttributes != nil {
		in, out := &in.LabelsAttributes, &out.LabelsAttributes
		*out = make([]K8sLabelAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AnnotationsAttributes != nil {
		in, out := &in.AnnotationsAttributes, &out.AnnotationsAttributes
		*out = make([]K8sAnnotationAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAttributesConfig.
func (in *K8sAttributesConfig) DeepCopy() *K8sAttributesConfig {
	if in == nil {
		return nil
	}
	out := new(K8sAttributesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAttributesResolver) DeepCopyInto(out *K8sAttributesResolver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAttributesResolver.
func (in *K8sAttributesResolver) DeepCopy() *K8sAttributesResolver {
	if in == nil {
		return nil
	}
	out := new(K8sAttributesResolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K8sAttributesResolver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAttributesResolverList) DeepCopyInto(out *K8sAttributesResolverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K8sAttributesResolver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAttributesResolverList.
func (in *K8sAttributesResolverList) DeepCopy() *K8sAttributesResolverList {
	if in == nil {
		return nil
	}
	out := new(K8sAttributesResolverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K8sAttributesResolverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAttributesSpec) DeepCopyInto(out *K8sAttributesSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.LabelsAttributes != nil {
		in, out := &in.LabelsAttributes, &out.LabelsAttributes
		*out = make([]K8sLabelAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AnnotationsAttributes != nil {
		in, out := &in.AnnotationsAttributes, &out.AnnotationsAttributes
		*out = make([]K8sAnnotationAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAttributesSpec.
func (in *K8sAttributesSpec) DeepCopy() *K8sAttributesSpec {
	if in == nil {
		return nil
	}
	out := new(K8sAttributesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAttributesStatus) DeepCopyInto(out *K8sAttributesStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAttributesStatus.
func (in *K8sAttributesStatus) DeepCopy() *K8sAttributesStatus {
	if in == nil {
		return nil
	}
	out := new(K8sAttributesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sLabelAttribute) DeepCopyInto(out *K8sLabelAttribute) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(K8sAttributeSource)
		**out = **in
	}
	if in.FromSources != nil {
		in, out := &in.FromSources, &out.FromSources
		*out = make([]K8sAttributeSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sLabelAttribute.
func (in *K8sLabelAttribute) DeepCopy() *K8sLabelAttribute {
	if in == nil {
		return nil
	}
	out := new(K8sLabelAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencySampler) DeepCopyInto(out *LatencySampler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencySampler.
func (in *LatencySampler) DeepCopy() *LatencySampler {
	if in == nil {
		return nil
	}
	out := new(LatencySampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LatencySampler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencySamplerConfig) DeepCopyInto(out *LatencySamplerConfig) {
	*out = *in
	if in.EndpointsFilters != nil {
		in, out := &in.EndpointsFilters, &out.EndpointsFilters
		*out = make([]HttpRouteFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencySamplerConfig.
func (in *LatencySamplerConfig) DeepCopy() *LatencySamplerConfig {
	if in == nil {
		return nil
	}
	out := new(LatencySamplerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencySamplerList) DeepCopyInto(out *LatencySamplerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LatencySampler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencySamplerList.
func (in *LatencySamplerList) DeepCopy() *LatencySamplerList {
	if in == nil {
		return nil
	}
	out := new(LatencySamplerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LatencySamplerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencySamplerSpec) DeepCopyInto(out *LatencySamplerSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.EndpointsFilters != nil {
		in, out := &in.EndpointsFilters, &out.EndpointsFilters
		*out = make([]HttpRouteFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencySamplerSpec.
func (in *LatencySamplerSpec) DeepCopy() *LatencySamplerSpec {
	if in == nil {
		return nil
	}
	out := new(LatencySamplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencySamplerStatus) DeepCopyInto(out *LatencySamplerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencySamplerStatus.
func (in *LatencySamplerStatus) DeepCopy() *LatencySamplerStatus {
	if in == nil {
		return nil
	}
	out := new(LatencySamplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumberAttributeCondition) DeepCopyInto(out *NumberAttributeCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumberAttributeCondition.
func (in *NumberAttributeCondition) DeepCopy() *NumberAttributeCondition {
	if in == nil {
		return nil
	}
	out := new(NumberAttributeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelAttributeWithValue) DeepCopyInto(out *OtelAttributeWithValue) {
	*out = *in
	if in.AttributeStringValue != nil {
		in, out := &in.AttributeStringValue, &out.AttributeStringValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelAttributeWithValue.
func (in *OtelAttributeWithValue) DeepCopy() *OtelAttributeWithValue {
	if in == nil {
		return nil
	}
	out := new(OtelAttributeWithValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiiMasking) DeepCopyInto(out *PiiMasking) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiiMasking.
func (in *PiiMasking) DeepCopy() *PiiMasking {
	if in == nil {
		return nil
	}
	out := new(PiiMasking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiiMasking) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiiMaskingConfig) DeepCopyInto(out *PiiMaskingConfig) {
	*out = *in
	if in.PiiCategories != nil {
		in, out := &in.PiiCategories, &out.PiiCategories
		*out = make([]PiiCategory, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiiMaskingConfig.
func (in *PiiMaskingConfig) DeepCopy() *PiiMaskingConfig {
	if in == nil {
		return nil
	}
	out := new(PiiMaskingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiiMaskingList) DeepCopyInto(out *PiiMaskingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiiMasking, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiiMaskingList.
func (in *PiiMaskingList) DeepCopy() *PiiMaskingList {
	if in == nil {
		return nil
	}
	out := new(PiiMaskingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiiMaskingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiiMaskingSpec) DeepCopyInto(out *PiiMaskingSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.PiiCategories != nil {
		in, out := &in.PiiCategories, &out.PiiCategories
		*out = make([]PiiCategory, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiiMaskingSpec.
func (in *PiiMaskingSpec) DeepCopy() *PiiMaskingSpec {
	if in == nil {
		return nil
	}
	out := new(PiiMaskingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiiMaskingStatus) DeepCopyInto(out *PiiMaskingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiiMaskingStatus.
func (in *PiiMaskingStatus) DeepCopy() *PiiMaskingStatus {
	if in == nil {
		return nil
	}
	out := new(PiiMaskingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbabilisticSampler) DeepCopyInto(out *ProbabilisticSampler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbabilisticSampler.
func (in *ProbabilisticSampler) DeepCopy() *ProbabilisticSampler {
	if in == nil {
		return nil
	}
	out := new(ProbabilisticSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProbabilisticSampler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbabilisticSamplerConfig) DeepCopyInto(out *ProbabilisticSamplerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbabilisticSamplerConfig.
func (in *ProbabilisticSamplerConfig) DeepCopy() *ProbabilisticSamplerConfig {
	if in == nil {
		return nil
	}
	out := new(ProbabilisticSamplerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbabilisticSamplerList) DeepCopyInto(out *ProbabilisticSamplerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProbabilisticSampler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbabilisticSamplerList.
func (in *ProbabilisticSamplerList) DeepCopy() *ProbabilisticSamplerList {
	if in == nil {
		return nil
	}
	out := new(ProbabilisticSamplerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProbabilisticSamplerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbabilisticSamplerSpec) DeepCopyInto(out *ProbabilisticSamplerSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbabilisticSamplerSpec.
func (in *ProbabilisticSamplerSpec) DeepCopy() *ProbabilisticSamplerSpec {
	if in == nil {
		return nil
	}
	out := new(ProbabilisticSamplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbabilisticSamplerStatus) DeepCopyInto(out *ProbabilisticSamplerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbabilisticSamplerStatus.
func (in *ProbabilisticSamplerStatus) DeepCopy() *ProbabilisticSamplerStatus {
	if in == nil {
		return nil
	}
	out := new(ProbabilisticSamplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameAttribute) DeepCopyInto(out *RenameAttribute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameAttribute.
func (in *RenameAttribute) DeepCopy() *RenameAttribute {
	if in == nil {
		return nil
	}
	out := new(RenameAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RenameAttribute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameAttributeConfig) DeepCopyInto(out *RenameAttributeConfig) {
	*out = *in
	if in.Renames != nil {
		in, out := &in.Renames, &out.Renames
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameAttributeConfig.
func (in *RenameAttributeConfig) DeepCopy() *RenameAttributeConfig {
	if in == nil {
		return nil
	}
	out := new(RenameAttributeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameAttributeList) DeepCopyInto(out *RenameAttributeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RenameAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameAttributeList.
func (in *RenameAttributeList) DeepCopy() *RenameAttributeList {
	if in == nil {
		return nil
	}
	out := new(RenameAttributeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RenameAttributeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameAttributeSpec) DeepCopyInto(out *RenameAttributeSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.Renames != nil {
		in, out := &in.Renames, &out.Renames
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameAttributeSpec.
func (in *RenameAttributeSpec) DeepCopy() *RenameAttributeSpec {
	if in == nil {
		return nil
	}
	out := new(RenameAttributeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenameAttributeStatus) DeepCopyInto(out *RenameAttributeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenameAttributeStatus.
func (in *RenameAttributeStatus) DeepCopy() *RenameAttributeStatus {
	if in == nil {
		return nil
	}
	out := new(RenameAttributeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SamplersConfig) DeepCopyInto(out *SamplersConfig) {
	*out = *in
	out.DefaultSamplerConfig = in.DefaultSamplerConfig
	if in.ErrorSampler != nil {
		in, out := &in.ErrorSampler, &out.ErrorSampler
		*out = new(ErrorSamplerConfig)
		**out = **in
	}
	if in.LatencySampler != nil {
		in, out := &in.LatencySampler, &out.LatencySampler
		*out = new(LatencySamplerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceNameSampler != nil {
		in, out := &in.ServiceNameSampler, &out.ServiceNameSampler
		*out = new(ServiceNameSamplerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SpanAttributeSampler != nil {
		in, out := &in.SpanAttributeSampler, &out.SpanAttributeSampler
		*out = new(SpanAttributeSamplerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProbabilisticSampler != nil {
		in, out := &in.ProbabilisticSampler, &out.ProbabilisticSampler
		*out = new(ProbabilisticSamplerConfig)
		**out = **in
	}
	if in.IgnoreHealthChecks != nil {
		in, out := &in.IgnoreHealthChecks, &out.IgnoreHealthChecks
		*out = new(IgnoreHealthChecksConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SamplersConfig.
func (in *SamplersConfig) DeepCopy() *SamplersConfig {
	if in == nil {
		return nil
	}
	out := new(SamplersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNameFilter) DeepCopyInto(out *ServiceNameFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNameFilter.
func (in *ServiceNameFilter) DeepCopy() *ServiceNameFilter {
	if in == nil {
		return nil
	}
	out := new(ServiceNameFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNameSampler) DeepCopyInto(out *ServiceNameSampler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNameSampler.
func (in *ServiceNameSampler) DeepCopy() *ServiceNameSampler {
	if in == nil {
		return nil
	}
	out := new(ServiceNameSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceNameSampler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNameSamplerConfig) DeepCopyInto(out *ServiceNameSamplerConfig) {
	*out = *in
	if in.ServicesNameFilters != nil {
		in, out := &in.ServicesNameFilters, &out.ServicesNameFilters
		*out = make([]ServiceNameFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNameSamplerConfig.
func (in *ServiceNameSamplerConfig) DeepCopy() *ServiceNameSamplerConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceNameSamplerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNameSamplerList) DeepCopyInto(out *ServiceNameSamplerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceNameSampler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNameSamplerList.
func (in *ServiceNameSamplerList) DeepCopy() *ServiceNameSamplerList {
	if in == nil {
		return nil
	}
	out := new(ServiceNameSamplerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceNameSamplerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNameSamplerSpec) DeepCopyInto(out *ServiceNameSamplerSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.ServicesNameFilters != nil {
		in, out := &in.ServicesNameFilters, &out.ServicesNameFilters
		*out = make([]ServiceNameFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNameSamplerSpec.
func (in *ServiceNameSamplerSpec) DeepCopy() *ServiceNameSamplerSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceNameSamplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNameSamplerStatus) DeepCopyInto(out *ServiceNameSamplerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNameSamplerStatus.
func (in *ServiceNameSamplerStatus) DeepCopy() *ServiceNameSamplerStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceNameSamplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanAttributeFilter) DeepCopyInto(out *SpanAttributeFilter) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanAttributeFilter.
func (in *SpanAttributeFilter) DeepCopy() *SpanAttributeFilter {
	if in == nil {
		return nil
	}
	out := new(SpanAttributeFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanAttributeSampler) DeepCopyInto(out *SpanAttributeSampler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanAttributeSampler.
func (in *SpanAttributeSampler) DeepCopy() *SpanAttributeSampler {
	if in == nil {
		return nil
	}
	out := new(SpanAttributeSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpanAttributeSampler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanAttributeSamplerConfig) DeepCopyInto(out *SpanAttributeSamplerConfig) {
	*out = *in
	if in.AttributeFilters != nil {
		in, out := &in.AttributeFilters, &out.AttributeFilters
		*out = make([]SpanAttributeFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanAttributeSamplerConfig.
func (in *SpanAttributeSamplerConfig) DeepCopy() *SpanAttributeSamplerConfig {
	if in == nil {
		return nil
	}
	out := new(SpanAttributeSamplerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanAttributeSamplerList) DeepCopyInto(out *SpanAttributeSamplerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpanAttributeSampler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanAttributeSamplerList.
func (in *SpanAttributeSamplerList) DeepCopy() *SpanAttributeSamplerList {
	if in == nil {
		return nil
	}
	out := new(SpanAttributeSamplerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpanAttributeSamplerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanAttributeSamplerSpec) DeepCopyInto(out *SpanAttributeSamplerSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.AttributeFilters != nil {
		in, out := &in.AttributeFilters, &out.AttributeFilters
		*out = make([]SpanAttributeFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanAttributeSamplerSpec.
func (in *SpanAttributeSamplerSpec) DeepCopy() *SpanAttributeSamplerSpec {
	if in == nil {
		return nil
	}
	out := new(SpanAttributeSamplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanAttributeSamplerStatus) DeepCopyInto(out *SpanAttributeSamplerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanAttributeSamplerStatus.
func (in *SpanAttributeSamplerStatus) DeepCopy() *SpanAttributeSamplerStatus {
	if in == nil {
		return nil
	}
	out := new(SpanAttributeSamplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringAttributeCondition) DeepCopyInto(out *StringAttributeCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringAttributeCondition.
func (in *StringAttributeCondition) DeepCopy() *StringAttributeCondition {
	if in == nil {
		return nil
	}
	out := new(StringAttributeCondition)
	in.DeepCopyInto(out)
	return out
}
