// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigossourcesfilterprocessor")
	ScopeName = "github.com/odigos-io/odigos/processor/odigossourcesfilterprocessor"
)

const (
	TracesStability  = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
	MetricsStability = component.StabilityLevelBeta
)
