export const ROUTES = {
  SETUP: '/setup',
  OVERVIEW: '/overview',
  SOURCES: '/sources',
  DESTINATIONS: '/destinations',
  ACTIONS: '/actions',
  NEW_DESTINATION: '/setup?state=destinations',
  MANAGE_DESTINATION: '/destinations/create/form?dest=',
  UPDATE_DESTINATION: 'destinations/manage?dest=',
  CREATE_DESTINATION: 'destinations/create',
  CREATE_SOURCE: '/sources/create',
  MANAGE_SOURCE: '/sources/manage',
  CHOOSE_DESTINATION: '/choose-destination',
  CHOOSE_SOURCES: '/choose-sources',
  CHOOSE_ACTIONS: '/choose-action',
};
