export const ROUTES = {
  SETUP: '/setup',
  OVERVIEW: '/overview',
  APP: '/',
  SOURCES: '/sources',
  INSTRUMENTATION_RULES: '/instrumentation-rules',
  DESTINATIONS: '/destinations',
  ACTIONS: '/actions',
  NEW_DESTINATION: '/setup?state=destinations',
  MANAGE_DESTINATION: '/create-destination?dest=',
  UPDATE_DESTINATION: 'edit-destination?dest=',
  CREATE_DESTINATION: '/select-destination',
  CREATE_SOURCE: '/select-sources',
  MANAGE_SOURCE: '/edit-source',
  CHOOSE_DESTINATION: '/choose-destination',
  CHOOSE_SOURCES: '/choose-sources',
  CHOOSE_ACTIONS: '/choose-action',
  EDIT_ACTION: '/edit-action',
};
