// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigoslogsresourceattrsprocessor")
	ScopeName = "github.com/odigos-io/odigos/collector/processor/odigoslogsresourceattrsprocessor"
)

const (
	LogsStability = component.StabilityLevelBeta
)
