apiVersion: internal.odigos.io/v1beta1
kind: Status
metadata:
  name: auto-rollback
spec:
  type: 'AutoRollback'
  codegen:
    statusName: AutoRollbackStatus
    typeName: AutoRollbackReason
    constPrefix: AutoRollbackReason
    package: conditions
    outputFile: rollback_gen.go
  reasons:
  - name: "Disabled"
    message: "Auto rollback is disabled in the odigos configuration"
    odigosSeverity: "irrelevant"
  - name: "AgentNotEnabled"
    message: "odigos agent is not set to run with this source, auto rollback is not applicable"
    odigosSeverity: "irrelevant"
  - name: "RollbackOccurred"
    message: "odigos detected a crash and rolled back the source to protect your application"
    odigosSeverity: "notice"
  - name: "NotApplicable"
    message: "no stability check for source that odigos agent is not restarting"
    odigosSeverity: "irrelevant"
  - name: "WaitingForRollout"
    message: "source stability will be checked after the source is rolled out by odigos"
    odigosSeverity: "waiting"
  - name: "Evaluating"
    message: "evaluating pods stability"
    odigosSeverity: "success"
  - name: "Stable"
    message: "pods are stable after instrumentation"
    odigosSeverity: "success"
