apiVersion: internal.odigos.io/v1beta1
kind: Status
metadata:
  name: pods-injection
spec:
  type: 'PodsInjection'
  reasons:
  - name: "NoRunningPods"
    message: "source has no running pods"
    odigosSeverity: "Irrelevant"
  - name: "PodsInjectionNotRequired"
    message: "agent is injected to running pods automatically, restart of pods is not required"
    k8sConditionStatus: "True"
    odigosSeverity: "Success"
  - name: "PodsInjectedSuccessfully"
    message: "all pods of this source are successfully injected with odigos agent"
    k8sConditionStatus: "True"
    odigosSeverity: "Success"
  - name: "PodsOutOfDateAgent"
    message: "some pods of this source are running outdated odigos agent version or configuration"
    k8sConditionStatus: "False"
    odigosSeverity: "Error"
