// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigosextractattribute")
	ScopeName = "github.com/odigos-io/odigos/collector/processor/odigosextractattributeprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
