// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the connector/serviceio component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("serviceio")
	ScopeName = "github.com/odigos-io/odigos/collector/connector/serviceioconnector"
)

const (
	TracesToMetricsStability = component.StabilityLevelAlpha
)
