// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/odigos_trace_filter component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigos_trace_filter")
	ScopeName = "github.com/odigos-io/odigos/collector/processors/odigostracefilterprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
