{{- if include "odigos.createEnterpriseRegistryPullSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odigos.enterpriseRegistryPullSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
    odigos.io/central-system-object: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "odigos.enterpriseRegistryDockerConfigJson" . | b64enc }}
{{- end }}
