apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "odigos.ownerReferences" . | nindent 2 }}
  name: odigos-own-telemetry-otel-config
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
data:
  OTEL_SDK_DISABLED: "true"
