// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("googlecloudstorage")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/odigos/exporter/googlecloudstorageexporter"
)

const (
	TracesStability = component.StabilityLevelBeta
	LogsStability   = component.StabilityLevelBeta
)
