// Code generated by "make -C status generate"; DO NOT EDIT.

package conditions

const AutoRollbackStatus = "AutoRollback"

// +kubebuilder:validation:Enum=Disabled;AgentNotEnabled;RollbackOccurred;NotApplicable;WaitingForRollout;Evaluating;Stable
type AutoRollbackReason string

const (
	// Auto rollback is disabled in the odigos configuration
	AutoRollbackReasonDisabled AutoRollbackReason = "Disabled"
	// odigos agent is not set to run with this source, auto rollback is not applicable
	AutoRollbackReasonAgentNotEnabled AutoRollbackReason = "AgentNotEnabled"
	// odigos detected a crash and rolled back the source to protect your application
	AutoRollbackReasonRollbackOccurred AutoRollbackReason = "RollbackOccurred"
	// no stability check for source that odigos agent is not restarting
	AutoRollbackReasonNotApplicable AutoRollbackReason = "NotApplicable"
	// source stability will be checked after the source is rolled out by odigos
	AutoRollbackReasonWaitingForRollout AutoRollbackReason = "WaitingForRollout"
	// evaluating pods stability
	AutoRollbackReasonEvaluating AutoRollbackReason = "Evaluating"
	// pods are stable after instrumentation
	AutoRollbackReasonStable AutoRollbackReason = "Stable"
)
