# Dockerfile.alpine
FROM python:3.10.15-alpine
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir django

# Install dependencies from requirements.txt
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Supress health check endpoint from tracing
ENV OTEL_PYTHON_DJANGO_EXCLUDED_URLS=health/

RUN apk add sqlite

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]