// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigostracestate")
	ScopeName = "github.com/odigos-io/odigos/collector/processors/odigostracestateprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
