// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the exporter/azureblobstorage component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("azureblobstorage")
	ScopeName = "github.com/odigos-io/odigos/collector/exporter/azureblobstorageexporter"
)

const (
	TracesStability = component.StabilityLevelBeta
	LogsStability   = component.StabilityLevelBeta
)
