//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package common

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceHostMetricsConfiguration) DeepCopyInto(out *MetricsSourceHostMetricsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceHostMetricsConfiguration.
func (in *MetricsSourceHostMetricsConfiguration) DeepCopy() *MetricsSourceHostMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceHostMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceKubeletStatsConfiguration) DeepCopyInto(out *MetricsSourceKubeletStatsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceKubeletStatsConfiguration.
func (in *MetricsSourceKubeletStatsConfiguration) DeepCopy() *MetricsSourceKubeletStatsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceKubeletStatsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceSpanMetricsConfiguration) DeepCopyInto(out *MetricsSourceSpanMetricsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalDimensions != nil {
		in, out := &in.AdditionalDimensions, &out.AdditionalDimensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExplicitHistogramBuckets != nil {
		in, out := &in.ExplicitHistogramBuckets, &out.ExplicitHistogramBuckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceSpanMetricsConfiguration.
func (in *MetricsSourceSpanMetricsConfiguration) DeepCopy() *MetricsSourceSpanMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceSpanMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtlpExporterConfiguration) DeepCopyInto(out *OtlpExporterConfiguration) {
	*out = *in
	if in.EnableDataCompression != nil {
		in, out := &in.EnableDataCompression, &out.EnableDataCompression
		*out = new(bool)
		**out = **in
	}
	if in.RetryOnFailure != nil {
		in, out := &in.RetryOnFailure, &out.RetryOnFailure
		*out = new(RetryOnFailure)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtlpExporterConfiguration.
func (in *OtlpExporterConfiguration) DeepCopy() *OtlpExporterConfiguration {
	if in == nil {
		return nil
	}
	out := new(OtlpExporterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryOnFailure) DeepCopyInto(out *RetryOnFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryOnFailure.
func (in *RetryOnFailure) DeepCopy() *RetryOnFailure {
	if in == nil {
		return nil
	}
	out := new(RetryOnFailure)
	in.DeepCopyInto(out)
	return out
}
