//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package common

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceAgentJavaRuntimeMetricsConfiguration) DeepCopyInto(out *MetricsSourceAgentJavaRuntimeMetricsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricsSourceAgentRuntimeMetricConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceAgentJavaRuntimeMetricsConfiguration.
func (in *MetricsSourceAgentJavaRuntimeMetricsConfiguration) DeepCopy() *MetricsSourceAgentJavaRuntimeMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceAgentJavaRuntimeMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceAgentMetricsConfiguration) DeepCopyInto(out *MetricsSourceAgentMetricsConfiguration) {
	*out = *in
	if in.SpanMetrics != nil {
		in, out := &in.SpanMetrics, &out.SpanMetrics
		*out = new(MetricsSourceAgentSpanMetricsConfiguration)
		**out = **in
	}
	if in.RuntimeMetrics != nil {
		in, out := &in.RuntimeMetrics, &out.RuntimeMetrics
		*out = new(MetricsSourceAgentRuntimeMetricsConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceAgentMetricsConfiguration.
func (in *MetricsSourceAgentMetricsConfiguration) DeepCopy() *MetricsSourceAgentMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceAgentMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceAgentRuntimeMetricConfiguration) DeepCopyInto(out *MetricsSourceAgentRuntimeMetricConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceAgentRuntimeMetricConfiguration.
func (in *MetricsSourceAgentRuntimeMetricConfiguration) DeepCopy() *MetricsSourceAgentRuntimeMetricConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceAgentRuntimeMetricConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceAgentRuntimeMetricsConfiguration) DeepCopyInto(out *MetricsSourceAgentRuntimeMetricsConfiguration) {
	*out = *in
	if in.Java != nil {
		in, out := &in.Java, &out.Java
		*out = new(MetricsSourceAgentJavaRuntimeMetricsConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceAgentRuntimeMetricsConfiguration.
func (in *MetricsSourceAgentRuntimeMetricsConfiguration) DeepCopy() *MetricsSourceAgentRuntimeMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceAgentRuntimeMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceAgentSpanMetricsConfiguration) DeepCopyInto(out *MetricsSourceAgentSpanMetricsConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceAgentSpanMetricsConfiguration.
func (in *MetricsSourceAgentSpanMetricsConfiguration) DeepCopy() *MetricsSourceAgentSpanMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceAgentSpanMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceConfiguration) DeepCopyInto(out *MetricsSourceConfiguration) {
	*out = *in
	if in.SpanMetrics != nil {
		in, out := &in.SpanMetrics, &out.SpanMetrics
		*out = new(MetricsSourceSpanMetricsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.HostMetrics != nil {
		in, out := &in.HostMetrics, &out.HostMetrics
		*out = new(MetricsSourceHostMetricsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeletStats != nil {
		in, out := &in.KubeletStats, &out.KubeletStats
		*out = new(MetricsSourceKubeletStatsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OdigosOwnMetrics != nil {
		in, out := &in.OdigosOwnMetrics, &out.OdigosOwnMetrics
		*out = new(MetricsSourceOdigosOwnMetricsConfiguration)
		**out = **in
	}
	if in.AgentMetrics != nil {
		in, out := &in.AgentMetrics, &out.AgentMetrics
		*out = new(MetricsSourceAgentMetricsConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceConfiguration.
func (in *MetricsSourceConfiguration) DeepCopy() *MetricsSourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceHostMetricsConfiguration) DeepCopyInto(out *MetricsSourceHostMetricsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceHostMetricsConfiguration.
func (in *MetricsSourceHostMetricsConfiguration) DeepCopy() *MetricsSourceHostMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceHostMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceKubeletStatsConfiguration) DeepCopyInto(out *MetricsSourceKubeletStatsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceKubeletStatsConfiguration.
func (in *MetricsSourceKubeletStatsConfiguration) DeepCopy() *MetricsSourceKubeletStatsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceKubeletStatsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceOdigosOwnMetricsConfiguration) DeepCopyInto(out *MetricsSourceOdigosOwnMetricsConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceOdigosOwnMetricsConfiguration.
func (in *MetricsSourceOdigosOwnMetricsConfiguration) DeepCopy() *MetricsSourceOdigosOwnMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceOdigosOwnMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceSpanMetricsConfiguration) DeepCopyInto(out *MetricsSourceSpanMetricsConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalDimensions != nil {
		in, out := &in.AdditionalDimensions, &out.AdditionalDimensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExplicitHistogramBuckets != nil {
		in, out := &in.ExplicitHistogramBuckets, &out.ExplicitHistogramBuckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludedProcessInDimensions != nil {
		in, out := &in.IncludedProcessInDimensions, &out.IncludedProcessInDimensions
		*out = new(bool)
		**out = **in
	}
	if in.ExcludedResourceAttributes != nil {
		in, out := &in.ExcludedResourceAttributes, &out.ExcludedResourceAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceMetricsKeyAttributes != nil {
		in, out := &in.ResourceMetricsKeyAttributes, &out.ResourceMetricsKeyAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceSpanMetricsConfiguration.
func (in *MetricsSourceSpanMetricsConfiguration) DeepCopy() *MetricsSourceSpanMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceSpanMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtlpExporterConfiguration) DeepCopyInto(out *OtlpExporterConfiguration) {
	*out = *in
	if in.EnableDataCompression != nil {
		in, out := &in.EnableDataCompression, &out.EnableDataCompression
		*out = new(bool)
		**out = **in
	}
	if in.RetryOnFailure != nil {
		in, out := &in.RetryOnFailure, &out.RetryOnFailure
		*out = new(RetryOnFailure)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtlpExporterConfiguration.
func (in *OtlpExporterConfiguration) DeepCopy() *OtlpExporterConfiguration {
	if in == nil {
		return nil
	}
	out := new(OtlpExporterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryOnFailure) DeepCopyInto(out *RetryOnFailure) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryOnFailure.
func (in *RetryOnFailure) DeepCopy() *RetryOnFailure {
	if in == nil {
		return nil
	}
	out := new(RetryOnFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailSamplingConfiguration) DeepCopyInto(out *TailSamplingConfiguration) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.TraceAggregationWaitDuration != nil {
		in, out := &in.TraceAggregationWaitDuration, &out.TraceAggregationWaitDuration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailSamplingConfiguration.
func (in *TailSamplingConfiguration) DeepCopy() *TailSamplingConfiguration {
	if in == nil {
		return nil
	}
	out := new(TailSamplingConfiguration)
	in.DeepCopyInto(out)
	return out
}
