{{- $metricsStoreDisabled := false }}
{{- if .Values.ownTelemetry }}
  {{- if .Values.ownTelemetry.metricsStore }}
    {{- if hasKey .Values.ownTelemetry.metricsStore "disabled" }}
      {{- $metricsStoreDisabled = .Values.ownTelemetry.metricsStore.disabled }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if not $metricsStoreDisabled }}
apiVersion: v1
kind: Service
metadata:
  name: odigos-victoriametrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: odigos-victoriametrics
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8428
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: odigos-victoriametrics

{{- end }}
