{{- if .Values.onPremToken }}
apiVersion: v1
kind: Secret
metadata:
  name: odigos-pro
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
stringData:
  odigos-onprem-token: {{ .Values.onPremToken }}
{{- else if .Values.marketplace.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: odigos-pro
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
stringData:
  aws-marketplace: "true"
{{- end }}
