{{- if .Values.onPremToken }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "odigos.ownerReferences" . | nindent 2 }}
  name: odigos-pro
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
stringData:
  odigos-onprem-token: {{ .Values.onPremToken }}
{{- end }}
