{{- if .Values.aiden.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: odigos-aiden
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: odigos-aiden
    odigos.io/system-object: "true"
type: Opaque
data:
  gemini-api-key: {{ .Values.aiden.gemini.key | default "" | b64enc }}
  slack-app-token: {{ .Values.aiden.slack.key | default "" | b64enc }}
  slack-bot-token: {{ .Values.aiden.slack.botToken | default "" | b64enc }}
{{- end }}
