#!/usr/bin/env bash
# Extract agent image tags (including @sha256 digests) from odiglet Dockerfiles
# and write a versions file for docker-bake.hcl / depot.mk.
#
# Usage:
#   sync-agent-versions.sh <versions-out> --from <dockerfile> <agent> [<agent> ...]
#                          [--from <dockerfile> <agent> [<agent> ...]]...
#
# Example:
#   sync-agent-versions.sh docker/odiglet/versions \
#     --from ../odigos/odiglet/Dockerfile nodejs-community nodejs-community-14 php-community ruby-community
#
#   sync-agent-versions.sh docker/enterprise-odiglet/versions \
#     --from ../odigos-enterprise/odiglet/Dockerfile \
#       nodejs-enterprise nodejs-enterprise-14 java-ebpf-instrumentations java-enterprise \
#     --from ../odigos/odiglet/Dockerfile php-community ruby-community
set -euo pipefail

if [[ $# -lt 4 || "$1" == -* ]]; then
  echo "Usage: $0 <versions-out> --from <dockerfile> <agent> [<agent> ...] [--from ...]" >&2
  exit 1
fi

versions_out=$1
shift

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

sources=()

extract_agents() {
  local dockerfile=$1
  shift
  local agents=("$@")

  if [[ ! -f "$dockerfile" ]]; then
    echo "Error: Dockerfile not found: $dockerfile" >&2
    exit 1
  fi

  sources+=("$dockerfile")

  local agent ver
  for agent in "${agents[@]}"; do
    # First COPY --from=.../agents/<agent>:<tag>[@sha256:...] wins (dedupe repeats).
    ver=$(grep -oE "agents/${agent}:[^[:space:]]+" "$dockerfile" | head -n1 | sed "s|^agents/${agent}:||") || true
    if [[ -z "${ver}" ]]; then
      echo "Error: agent '${agent}' not found in ${dockerfile}" >&2
      exit 1
    fi
    echo "${agent}=${ver}"
  done
}

{
  echo "# Auto-generated — do not edit by hand."
  echo "# Regenerated by scripts/sync-agent-versions.sh before depot bake."

  while [[ $# -gt 0 ]]; do
    if [[ "$1" != "--from" ]]; then
      echo "Error: expected --from, got: $1" >&2
      exit 1
    fi
    shift
    if [[ $# -lt 1 ]]; then
      echo "Error: --from requires a Dockerfile path" >&2
      exit 1
    fi
    dockerfile=$1
    shift

    agents=()
    while [[ $# -gt 0 && "$1" != "--from" ]]; do
      agents+=("$1")
      shift
    done
    if [[ ${#agents[@]} -eq 0 ]]; then
      echo "Error: --from ${dockerfile} requires at least one agent name" >&2
      exit 1
    fi

    extract_agents "$dockerfile" "${agents[@]}"
  done
} >"$tmp"

# Rewrite header with source list now that we know them.
{
  echo "# Auto-generated from: ${sources[*]} — do not edit by hand."
  echo "# Regenerated by scripts/sync-agent-versions.sh before depot bake."
  grep -E '^[a-z0-9-]+=.' "$tmp"
} >"${tmp}.out"
mv "${tmp}.out" "$tmp"

mkdir -p "$(dirname "$versions_out")"
mv "$tmp" "$versions_out"
trap - EXIT

echo "Wrote ${versions_out}:"
cat "$versions_out"
