name: "Setup AWS Credentials"
description: "Automatically configures AWS credentials for local runs (act) and GitHub Actions (OIDC)"
runs:
  using: "composite"
  steps:
    - name: Run AWS Setup Script
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        AWS_REGION: "us-east-1"
        AWS_ROLE_TO_ASSUME: "arn:aws:iam::061717858829:role/ecr-pull-push-role"