//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package actions

import (
	"github.com/odigos-io/odigos/api/k8sconsts"
	apiactions "github.com/odigos-io/odigos/common/api/actions"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbQueryTemplatizationConfig) DeepCopyInto(out *DbQueryTemplatizationConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = new(k8sconsts.SourcesScopes)
		(*in).DeepCopyInto(*out)
	}
	out.DbQueryTemplatizationConfig = in.DbQueryTemplatizationConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbQueryTemplatizationConfig.
func (in *DbQueryTemplatizationConfig) DeepCopy() *DbQueryTemplatizationConfig {
	if in == nil {
		return nil
	}
	out := new(DbQueryTemplatizationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtractAttributeConfig) DeepCopyInto(out *ExtractAttributeConfig) {
	*out = *in
	if in.Extractions != nil {
		in, out := &in.Extractions, &out.Extractions
		*out = make([]Extraction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtractAttributeConfig.
func (in *ExtractAttributeConfig) DeepCopy() *ExtractAttributeConfig {
	if in == nil {
		return nil
	}
	out := new(ExtractAttributeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extraction) DeepCopyInto(out *Extraction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extraction.
func (in *Extraction) DeepCopy() *Extraction {
	if in == nil {
		return nil
	}
	out := new(Extraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiiMaskingConfig) DeepCopyInto(out *PiiMaskingConfig) {
	*out = *in
	in.PiiMaskingConfig.DeepCopyInto(&out.PiiMaskingConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiiMaskingConfig.
func (in *PiiMaskingConfig) DeepCopy() *PiiMaskingConfig {
	if in == nil {
		return nil
	}
	out := new(PiiMaskingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanRenamerConfig) DeepCopyInto(out *SpanRenamerConfig) {
	*out = *in
	if in.RegexReplacements != nil {
		in, out := &in.RegexReplacements, &out.RegexReplacements
		*out = make([]apiactions.SpanRenamerRegexReplacement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanRenamerConfig.
func (in *SpanRenamerConfig) DeepCopy() *SpanRenamerConfig {
	if in == nil {
		return nil
	}
	out := new(SpanRenamerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLTemplatizationConfig) DeepCopyInto(out *URLTemplatizationConfig) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]UrlTemplatizationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = make([]URLTemplatizationDefaultTemplatizationGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLTemplatizationConfig.
func (in *URLTemplatizationConfig) DeepCopy() *URLTemplatizationConfig {
	if in == nil {
		return nil
	}
	out := new(URLTemplatizationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLTemplatizationDefaultTemplatizationGroup) DeepCopyInto(out *URLTemplatizationDefaultTemplatizationGroup) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = new(k8sconsts.SourcesScopes)
		(*in).DeepCopyInto(*out)
	}
	in.DefaultTemplatizationConfig.DeepCopyInto(&out.DefaultTemplatizationConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLTemplatizationDefaultTemplatizationGroup.
func (in *URLTemplatizationDefaultTemplatizationGroup) DeepCopy() *URLTemplatizationDefaultTemplatizationGroup {
	if in == nil {
		return nil
	}
	out := new(URLTemplatizationDefaultTemplatizationGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlTemplatizationRule) DeepCopyInto(out *UrlTemplatizationRule) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = new(k8sconsts.SourcesScopes)
		(*in).DeepCopyInto(*out)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlTemplatizationRule.
func (in *UrlTemplatizationRule) DeepCopy() *UrlTemplatizationRule {
	if in == nil {
		return nil
	}
	out := new(UrlTemplatizationRule)
	in.DeepCopyInto(out)
	return out
}
