{{- if .Values.reactor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odigos-reactor
  labels:
    odigos.io/system-object: "true"
rules:
  - apiGroups:
      - odigos.io
    resources:
      - instrumentationrules
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - odigos.io
    resources:
      - samplings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
{{- end }}
