apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odigos-instrumentor
  namespace: '{{ .Release.Namespace }}'
  labels:
    odigos.io/system-object: "true"
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - effective-config
      - odigos-deployment
      - odigos-go-offsets
    verbs:
      - patch
      - create
      - update
  - apiGroups:
      - odigos.io
    resources:
      - collectorsgroups
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - odigos.io
    resources:
      - collectorsgroups/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - destinations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - instrumentationrules
      - processors
    verbs:
      - get
      - list
      - watch
      - patch
      - delete
      - create
  - apiGroups:
      - odigos.io
    resources:
      - instrumentationrules/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - odigos.io
    resources:
      - actions
    verbs:
      - get
      - list
      - watch
      - patch
      - delete
      - create
  - apiGroups:
      - odigos.io
    resources:
      - samplings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - actions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - odigos.io
    resources:
      - samplings/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - instrumentor-webhooks-cert
    verbs:
      - update
# migration from the old webhook cert - this can be removed once we are confident that the old secrets have been deleted
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - webhook-cert
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - daemonsets
    resourceNames:
      - odiglet
    verbs:
      - get
      - list
      - watch
{{- if ne .Values.goAutoOffsetsMode "off" }}
  - apiGroups:
      - 'batch'
    resources:
      - cronjobs
    resourceNames:
      - 'odigos-go-offsets-updater'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - 'batch'
    resources:
      - 'jobs'
    verbs:
      - 'create'
{{- end }}
