apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "odigos.ownerReferences" . | nindent 2 }}
  name: odigos-instrumentor
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
