// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestValidateConfigs(t *testing.T) {
	factories, err := components()
	assert.NoError(t, err)

	// MakeFactoryMap may register deprecated type aliases as extra keys; alias keys differ from
	// factory.Type() but reference the same factory as factories.Map[factory.Type()].
	for k, factory := range factories.Receivers {
		assert.Equal(t, factory, factories.Receivers[factory.Type()])
		if k != factory.Type() {
			continue
		}
		assert.NoError(t, componenttest.CheckConfigStruct(factory.CreateDefaultConfig()))
	}

	for k, factory := range factories.Processors {
		assert.Equal(t, factory, factories.Processors[factory.Type()])
		if k != factory.Type() {
			continue
		}
		assert.NoError(t, componenttest.CheckConfigStruct(factory.CreateDefaultConfig()))
	}

	for k, factory := range factories.Exporters {
		assert.Equal(t, factory, factories.Exporters[factory.Type()])
		if k != factory.Type() {
			continue
		}
		assert.NoError(t, componenttest.CheckConfigStruct(factory.CreateDefaultConfig()))
	}

	for k, factory := range factories.Connectors {
		assert.Equal(t, factory, factories.Connectors[factory.Type()])
		if k != factory.Type() {
			continue
		}
		assert.NoError(t, componenttest.CheckConfigStruct(factory.CreateDefaultConfig()))
	}

	for k, factory := range factories.Extensions {
		assert.Equal(t, factory, factories.Extensions[factory.Type()])
		if k != factory.Type() {
			continue
		}
		assert.NoError(t, componenttest.CheckConfigStruct(factory.CreateDefaultConfig()))
	}
}
