// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/odigossqldboperationprocessor component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigossqldboperationprocessor")
	ScopeName = "odigossqldboperationprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
