issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:odigos-io(@84347062)?/odigos(@501095512)?:ref:refs/heads/main
claim_pattern:
  event_name: "(workflow_dispatch|repository_dispatch)"

permissions:
  contents: write
  pull_requests: write
