issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:odigos-io/(opentelemetry-node|opentelemetry-ruby|opentelemetry-php):ref:refs/tags/.*

permissions:

  # needed to trigger repository_dispatch event
  contents: write
