// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigostrafficmetrics")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/odigos/processor/odigostrafficmetrics"
)

const (
	LogsStability    = component.StabilityLevelBeta
	MetricsStability = component.StabilityLevelBeta
	TracesStability  = component.StabilityLevelBeta
)
