// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("odigostrafficmetrics")
)

const (
	LogsStability    = component.StabilityLevelBeta
	MetricsStability = component.StabilityLevelBeta
	TracesStability  = component.StabilityLevelBeta
)
