// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/odigos/processor/odigostrafficmetrics")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/odigos/processor/odigostrafficmetrics")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                      metric.Meter
	mu                         sync.Mutex
	registrations              []metric.Registration
	OdigosAcceptedLogRecords   metric.Int64Counter
	OdigosAcceptedMetricPoints metric.Int64Counter
	OdigosAcceptedSpans        metric.Int64Counter
	OdigosLogDataSize          metric.Int64Counter
	OdigosMetricDataSize       metric.Int64Counter
	OdigosTraceDataSize        metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.OdigosAcceptedLogRecords, err = builder.meter.Int64Counter(
		"otelcol_odigos_accepted_log_records",
		metric.WithDescription("Number of log records passed through the processor. [Development]"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.OdigosAcceptedMetricPoints, err = builder.meter.Int64Counter(
		"otelcol_odigos_accepted_metric_points",
		metric.WithDescription("Number of data points passed through the processor. [Development]"),
		metric.WithUnit("{datapoints}"),
	)
	errs = errors.Join(errs, err)
	builder.OdigosAcceptedSpans, err = builder.meter.Int64Counter(
		"otelcol_odigos_accepted_spans",
		metric.WithDescription("Number of spans passed through the processor. [Development]"),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.OdigosLogDataSize, err = builder.meter.Int64Counter(
		"otelcol_odigos_log_data_size",
		metric.WithDescription("Total size of log data passed to the processor [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.OdigosMetricDataSize, err = builder.meter.Int64Counter(
		"otelcol_odigos_metric_data_size",
		metric.WithDescription("Total size of metric data passed to the processor [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.OdigosTraceDataSize, err = builder.meter.Int64Counter(
		"otelcol_odigos_trace_data_size",
		metric.WithDescription("Total size of trace data passed to the processor [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
