//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/odigos-io/odigos/api/odigos/v1alpha1/instrumentationrules"
	"github.com/odigos-io/odigos/common"
	"github.com/odigos-io/odigos/k8sutils/pkg/workload"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attribute) DeepCopyInto(out *Attribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attribute.
func (in *Attribute) DeepCopy() *Attribute {
	if in == nil {
		return nil
	}
	out := new(Attribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeCondition) DeepCopyInto(out *AttributeCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeCondition.
func (in *AttributeCondition) DeepCopy() *AttributeCondition {
	if in == nil {
		return nil
	}
	out := new(AttributeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributesAndSamplerRule) DeepCopyInto(out *AttributesAndSamplerRule) {
	*out = *in
	if in.AttributeConditions != nil {
		in, out := &in.AttributeConditions, &out.AttributeConditions
		*out = make([]AttributeCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributesAndSamplerRule.
func (in *AttributesAndSamplerRule) DeepCopy() *AttributesAndSamplerRule {
	if in == nil {
		return nil
	}
	out := new(AttributesAndSamplerRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorGatewayConfiguration) DeepCopyInto(out *CollectorGatewayConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorGatewayConfiguration.
func (in *CollectorGatewayConfiguration) DeepCopy() *CollectorGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(CollectorGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorsGroup) DeepCopyInto(out *CollectorsGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorsGroup.
func (in *CollectorsGroup) DeepCopy() *CollectorsGroup {
	if in == nil {
		return nil
	}
	out := new(CollectorsGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectorsGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorsGroupList) DeepCopyInto(out *CollectorsGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CollectorsGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorsGroupList.
func (in *CollectorsGroupList) DeepCopy() *CollectorsGroupList {
	if in == nil {
		return nil
	}
	out := new(CollectorsGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectorsGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorsGroupResourcesSettings) DeepCopyInto(out *CollectorsGroupResourcesSettings) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorsGroupResourcesSettings.
func (in *CollectorsGroupResourcesSettings) DeepCopy() *CollectorsGroupResourcesSettings {
	if in == nil {
		return nil
	}
	out := new(CollectorsGroupResourcesSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorsGroupSpec) DeepCopyInto(out *CollectorsGroupSpec) {
	*out = *in
	in.ResourcesSettings.DeepCopyInto(&out.ResourcesSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorsGroupSpec.
func (in *CollectorsGroupSpec) DeepCopy() *CollectorsGroupSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorsGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorsGroupStatus) DeepCopyInto(out *CollectorsGroupStatus) {
	*out = *in
	if in.ReceiverSignals != nil {
		in, out := &in.ReceiverSignals, &out.ReceiverSignals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorsGroupStatus.
func (in *CollectorsGroupStatus) DeepCopy() *CollectorsGroupStatus {
	if in == nil {
		return nil
	}
	out := new(CollectorsGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOption) DeepCopyInto(out *ConfigOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOption.
func (in *ConfigOption) DeepCopy() *ConfigOption {
	if in == nil {
		return nil
	}
	out := new(ConfigOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Destination) DeepCopyInto(out *Destination) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Destination.
func (in *Destination) DeepCopy() *Destination {
	if in == nil {
		return nil
	}
	out := new(Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Destination) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationList) DeepCopyInto(out *DestinationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Destination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationList.
func (in *DestinationList) DeepCopy() *DestinationList {
	if in == nil {
		return nil
	}
	out := new(DestinationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DestinationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSpec) DeepCopyInto(out *DestinationSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSpec.
func (in *DestinationSpec) DeepCopy() *DestinationSpec {
	if in == nil {
		return nil
	}
	out := new(DestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationStatus) DeepCopyInto(out *DestinationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationStatus.
func (in *DestinationStatus) DeepCopy() *DestinationStatus {
	if in == nil {
		return nil
	}
	out := new(DestinationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadSamplingConfig) DeepCopyInto(out *HeadSamplingConfig) {
	*out = *in
	if in.AttributesAndSamplerRules != nil {
		in, out := &in.AttributesAndSamplerRules, &out.AttributesAndSamplerRules
		*out = make([]AttributesAndSamplerRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadSamplingConfig.
func (in *HeadSamplingConfig) DeepCopy() *HeadSamplingConfig {
	if in == nil {
		return nil
	}
	out := new(HeadSamplingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationConfig) DeepCopyInto(out *InstrumentationConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationConfig.
func (in *InstrumentationConfig) DeepCopy() *InstrumentationConfig {
	if in == nil {
		return nil
	}
	out := new(InstrumentationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationConfigList) DeepCopyInto(out *InstrumentationConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstrumentationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationConfigList.
func (in *InstrumentationConfigList) DeepCopy() *InstrumentationConfigList {
	if in == nil {
		return nil
	}
	out := new(InstrumentationConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationConfigSpec) DeepCopyInto(out *InstrumentationConfigSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]WorkloadInstrumentationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SdkConfigs != nil {
		in, out := &in.SdkConfigs, &out.SdkConfigs
		*out = make([]SdkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationConfigSpec.
func (in *InstrumentationConfigSpec) DeepCopy() *InstrumentationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(InstrumentationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationConfigStatus) DeepCopyInto(out *InstrumentationConfigStatus) {
	*out = *in
	if in.RuntimeDetailsByContainer != nil {
		in, out := &in.RuntimeDetailsByContainer, &out.RuntimeDetailsByContainer
		*out = make([]RuntimeDetailsByContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationConfigStatus.
func (in *InstrumentationConfigStatus) DeepCopy() *InstrumentationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(InstrumentationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationInstance) DeepCopyInto(out *InstrumentationInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationInstance.
func (in *InstrumentationInstance) DeepCopy() *InstrumentationInstance {
	if in == nil {
		return nil
	}
	out := new(InstrumentationInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationInstanceList) DeepCopyInto(out *InstrumentationInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstrumentationInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationInstanceList.
func (in *InstrumentationInstanceList) DeepCopy() *InstrumentationInstanceList {
	if in == nil {
		return nil
	}
	out := new(InstrumentationInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationInstanceSpec) DeepCopyInto(out *InstrumentationInstanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationInstanceSpec.
func (in *InstrumentationInstanceSpec) DeepCopy() *InstrumentationInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstrumentationInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationInstanceStatus) DeepCopyInto(out *InstrumentationInstanceStatus) {
	*out = *in
	if in.IdentifyingAttributes != nil {
		in, out := &in.IdentifyingAttributes, &out.IdentifyingAttributes
		*out = make([]Attribute, len(*in))
		copy(*out, *in)
	}
	if in.NonIdentifyingAttributes != nil {
		in, out := &in.NonIdentifyingAttributes, &out.NonIdentifyingAttributes
		*out = make([]Attribute, len(*in))
		copy(*out, *in)
	}
	if in.Healthy != nil {
		in, out := &in.Healthy, &out.Healthy
		*out = new(bool)
		**out = **in
	}
	in.LastStatusTime.DeepCopyInto(&out.LastStatusTime)
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]InstrumentationLibraryStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationInstanceStatus.
func (in *InstrumentationInstanceStatus) DeepCopy() *InstrumentationInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstrumentationInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibrary) DeepCopyInto(out *InstrumentationLibrary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibrary.
func (in *InstrumentationLibrary) DeepCopy() *InstrumentationLibrary {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibraryConfig) DeepCopyInto(out *InstrumentationLibraryConfig) {
	*out = *in
	out.InstrumentationLibraryId = in.InstrumentationLibraryId
	if in.TraceConfig != nil {
		in, out := &in.TraceConfig, &out.TraceConfig
		*out = new(InstrumentationLibraryConfigTraces)
		(*in).DeepCopyInto(*out)
	}
	if in.PayloadCollection != nil {
		in, out := &in.PayloadCollection, &out.PayloadCollection
		*out = new(instrumentationrules.PayloadCollection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibraryConfig.
func (in *InstrumentationLibraryConfig) DeepCopy() *InstrumentationLibraryConfig {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibraryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibraryConfigTraces) DeepCopyInto(out *InstrumentationLibraryConfigTraces) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibraryConfigTraces.
func (in *InstrumentationLibraryConfigTraces) DeepCopy() *InstrumentationLibraryConfigTraces {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibraryConfigTraces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibraryGlobalId) DeepCopyInto(out *InstrumentationLibraryGlobalId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibraryGlobalId.
func (in *InstrumentationLibraryGlobalId) DeepCopy() *InstrumentationLibraryGlobalId {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibraryGlobalId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibraryId) DeepCopyInto(out *InstrumentationLibraryId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibraryId.
func (in *InstrumentationLibraryId) DeepCopy() *InstrumentationLibraryId {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibraryId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibraryOptions) DeepCopyInto(out *InstrumentationLibraryOptions) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]ConfigOption, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibraryOptions.
func (in *InstrumentationLibraryOptions) DeepCopy() *InstrumentationLibraryOptions {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibraryOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationLibraryStatus) DeepCopyInto(out *InstrumentationLibraryStatus) {
	*out = *in
	if in.IdentifyingAttributes != nil {
		in, out := &in.IdentifyingAttributes, &out.IdentifyingAttributes
		*out = make([]Attribute, len(*in))
		copy(*out, *in)
	}
	if in.NonIdentifyingAttributes != nil {
		in, out := &in.NonIdentifyingAttributes, &out.NonIdentifyingAttributes
		*out = make([]Attribute, len(*in))
		copy(*out, *in)
	}
	if in.Healthy != nil {
		in, out := &in.Healthy, &out.Healthy
		*out = new(bool)
		**out = **in
	}
	in.LastStatusTime.DeepCopyInto(&out.LastStatusTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationLibraryStatus.
func (in *InstrumentationLibraryStatus) DeepCopy() *InstrumentationLibraryStatus {
	if in == nil {
		return nil
	}
	out := new(InstrumentationLibraryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationRule) DeepCopyInto(out *InstrumentationRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationRule.
func (in *InstrumentationRule) DeepCopy() *InstrumentationRule {
	if in == nil {
		return nil
	}
	out := new(InstrumentationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationRuleList) DeepCopyInto(out *InstrumentationRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstrumentationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationRuleList.
func (in *InstrumentationRuleList) DeepCopy() *InstrumentationRuleList {
	if in == nil {
		return nil
	}
	out := new(InstrumentationRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationRuleSpec) DeepCopyInto(out *InstrumentationRuleSpec) {
	*out = *in
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = new([]workload.PodWorkload)
		if **in != nil {
			in, out := *in, *out
			*out = make([]workload.PodWorkload, len(*in))
			copy(*out, *in)
		}
	}
	if in.InstrumentationLibraries != nil {
		in, out := &in.InstrumentationLibraries, &out.InstrumentationLibraries
		*out = new([]InstrumentationLibraryGlobalId)
		if **in != nil {
			in, out := *in, *out
			*out = make([]InstrumentationLibraryGlobalId, len(*in))
			copy(*out, *in)
		}
	}
	if in.PayloadCollection != nil {
		in, out := &in.PayloadCollection, &out.PayloadCollection
		*out = new(instrumentationrules.PayloadCollection)
		(*in).DeepCopyInto(*out)
	}
	if in.OtelSdks != nil {
		in, out := &in.OtelSdks, &out.OtelSdks
		*out = new(instrumentationrules.OtelSdks)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationRuleSpec.
func (in *InstrumentationRuleSpec) DeepCopy() *InstrumentationRuleSpec {
	if in == nil {
		return nil
	}
	out := new(InstrumentationRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationRuleStatus) DeepCopyInto(out *InstrumentationRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationRuleStatus.
func (in *InstrumentationRuleStatus) DeepCopy() *InstrumentationRuleStatus {
	if in == nil {
		return nil
	}
	out := new(InstrumentationRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentedApplication) DeepCopyInto(out *InstrumentedApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentedApplication.
func (in *InstrumentedApplication) DeepCopy() *InstrumentedApplication {
	if in == nil {
		return nil
	}
	out := new(InstrumentedApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentedApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentedApplicationList) DeepCopyInto(out *InstrumentedApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstrumentedApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentedApplicationList.
func (in *InstrumentedApplicationList) DeepCopy() *InstrumentedApplicationList {
	if in == nil {
		return nil
	}
	out := new(InstrumentedApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentedApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentedApplicationSpec) DeepCopyInto(out *InstrumentedApplicationSpec) {
	*out = *in
	if in.RuntimeDetails != nil {
		in, out := &in.RuntimeDetails, &out.RuntimeDetails
		*out = make([]RuntimeDetailsByContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]OptionByContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentedApplicationSpec.
func (in *InstrumentedApplicationSpec) DeepCopy() *InstrumentedApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(InstrumentedApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentedApplicationStatus) DeepCopyInto(out *InstrumentedApplicationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentedApplicationStatus.
func (in *InstrumentedApplicationStatus) DeepCopy() *InstrumentedApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(InstrumentedApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdigosConfiguration) DeepCopyInto(out *OdigosConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdigosConfiguration.
func (in *OdigosConfiguration) DeepCopy() *OdigosConfiguration {
	if in == nil {
		return nil
	}
	out := new(OdigosConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdigosConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdigosConfigurationList) DeepCopyInto(out *OdigosConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdigosConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdigosConfigurationList.
func (in *OdigosConfigurationList) DeepCopy() *OdigosConfigurationList {
	if in == nil {
		return nil
	}
	out := new(OdigosConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdigosConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdigosConfigurationSpec) DeepCopyInto(out *OdigosConfigurationSpec) {
	*out = *in
	if in.IgnoredNamespaces != nil {
		in, out := &in.IgnoredNamespaces, &out.IgnoredNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoredContainers != nil {
		in, out := &in.IgnoredContainers, &out.IgnoredContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CollectorGateway != nil {
		in, out := &in.CollectorGateway, &out.CollectorGateway
		*out = new(CollectorGatewayConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdigosConfigurationSpec.
func (in *OdigosConfigurationSpec) DeepCopy() *OdigosConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(OdigosConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionByContainer) DeepCopyInto(out *OptionByContainer) {
	*out = *in
	if in.InstrumentationLibraries != nil {
		in, out := &in.InstrumentationLibraries, &out.InstrumentationLibraries
		*out = make([]InstrumentationLibraryOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionByContainer.
func (in *OptionByContainer) DeepCopy() *OptionByContainer {
	if in == nil {
		return nil
	}
	out := new(OptionByContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtherAgent) DeepCopyInto(out *OtherAgent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtherAgent.
func (in *OtherAgent) DeepCopy() *OtherAgent {
	if in == nil {
		return nil
	}
	out := new(OtherAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Processor) DeepCopyInto(out *Processor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Processor.
func (in *Processor) DeepCopy() *Processor {
	if in == nil {
		return nil
	}
	out := new(Processor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Processor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorList) DeepCopyInto(out *ProcessorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Processor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorList.
func (in *ProcessorList) DeepCopy() *ProcessorList {
	if in == nil {
		return nil
	}
	out := new(ProcessorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcessorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorSpec) DeepCopyInto(out *ProcessorSpec) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]common.ObservabilitySignal, len(*in))
		copy(*out, *in)
	}
	if in.CollectorRoles != nil {
		in, out := &in.CollectorRoles, &out.CollectorRoles
		*out = make([]CollectorsGroupRole, len(*in))
		copy(*out, *in)
	}
	in.ProcessorConfig.DeepCopyInto(&out.ProcessorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorSpec.
func (in *ProcessorSpec) DeepCopy() *ProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(ProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorStatus) DeepCopyInto(out *ProcessorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorStatus.
func (in *ProcessorStatus) DeepCopy() *ProcessorStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeDetailsByContainer) DeepCopyInto(out *RuntimeDetailsByContainer) {
	*out = *in
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	if in.OtherAgent != nil {
		in, out := &in.OtherAgent, &out.OtherAgent
		*out = new(OtherAgent)
		**out = **in
	}
	if in.LibCType != nil {
		in, out := &in.LibCType, &out.LibCType
		*out = new(common.LibCType)
		**out = **in
	}
	if in.CriErrorMessage != nil {
		in, out := &in.CriErrorMessage, &out.CriErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.EnvVarsFromDockerFile != nil {
		in, out := &in.EnvVarsFromDockerFile, &out.EnvVarsFromDockerFile
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeUpdateState != nil {
		in, out := &in.RuntimeUpdateState, &out.RuntimeUpdateState
		*out = new(ProcessingState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeDetailsByContainer.
func (in *RuntimeDetailsByContainer) DeepCopy() *RuntimeDetailsByContainer {
	if in == nil {
		return nil
	}
	out := new(RuntimeDetailsByContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdkConfig) DeepCopyInto(out *SdkConfig) {
	*out = *in
	if in.InstrumentationLibraryConfigs != nil {
		in, out := &in.InstrumentationLibraryConfigs, &out.InstrumentationLibraryConfigs
		*out = make([]InstrumentationLibraryConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HeadSamplingConfig != nil {
		in, out := &in.HeadSamplingConfig, &out.HeadSamplingConfig
		*out = new(HeadSamplingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultPayloadCollection != nil {
		in, out := &in.DefaultPayloadCollection, &out.DefaultPayloadCollection
		*out = new(instrumentationrules.PayloadCollection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdkConfig.
func (in *SdkConfig) DeepCopy() *SdkConfig {
	if in == nil {
		return nil
	}
	out := new(SdkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadInstrumentationConfig) DeepCopyInto(out *WorkloadInstrumentationConfig) {
	*out = *in
	if in.InstrumentationLibraries != nil {
		in, out := &in.InstrumentationLibraries, &out.InstrumentationLibraries
		*out = make([]InstrumentationLibrary, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadInstrumentationConfig.
func (in *WorkloadInstrumentationConfig) DeepCopy() *WorkloadInstrumentationConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadInstrumentationConfig)
	in.DeepCopyInto(out)
	return out
}
