# Dockerfile.python38-slim
FROM python:3.8.0-slim
WORKDIR /app
COPY . /app

# Install dependencies from requirements.txt
COPY requirements.txt /app/requirements.txt

# Update apt sources to use archive repositories (Buster is EOL)
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list

    # Install build tools for compiling packages with C extensions
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    sqlite3

RUN pip install --no-cache-dir -r requirements.txt

# Supress health check endpoint from tracing
ENV OTEL_PYTHON_DJANGO_EXCLUDED_URLS=health/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]