# Dockerfile.python37-slim
FROM python:3.6-slim
WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install sqlite3 -y

RUN pip install --no-cache-dir -r requirements-legacy.txt

# Supress health check endpoint from tracing
ENV OTEL_PYTHON_DJANGO_EXCLUDED_URLS=health/

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]