name: Build images with depot

on:
  pull_request:
    branches: [ main, 'releases/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        id: build
        with:
          push: false
          context: .
          file: Dockerfile
          build-args: SERVICE_NAME=instrumentor
          
      - name: Show build outputs
        run: |
          echo "Image ID: ${{ steps.build.outputs.imageid }}"
          echo "Digest:   ${{ steps.build.outputs.digest }}"      
