name: full odigos build

on:
  pull_request:
    branches:
      - 'releases/**'
    types:
      - opened
      - synchronize
      - reopened
      
  schedule:
    - cron: '0 0 * * *' # Nightly run at midnight

  workflow_dispatch:

jobs:
  build-depot-images:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: depot/setup-action@v1
      - name: Build images with Depot
        run: make -j -f Makefile.depot depot-build-all
        env:
          IMAGE_TAG: v0.0.0-pr${{ github.event.number || github.run_number }}
          PLATFORM: linux/amd64,linux/arm64
          OUTPUT_DIR: /tmp

  build-all-services:
    name: build-all-services
    strategy:
      matrix:
        service: [instrumentor, odiglet, agents, frontend, operator]
        include:
          - service: instrumentor
            dockerfile_path: .
          - service: odiglet
            dockerfile_path: odiglet
          - service: agents
            dockerfile_path: odiglet
          - service: frontend
            dockerfile_path: frontend
          - service: operator
            dockerfile_path: operator
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build ${{ matrix.service }} Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          provenance: false
          file: ${{ matrix.dockerfile_path }}/Dockerfile
          context: .
          build-args: |
            SERVICE_NAME=${{ matrix.service }}
            ODIGOS_VERSION=v0.0.0-pr${{ github.event.number }}
          target: ${{ matrix.service == 'agents' && 'agents' || '' }}

  build-cli:
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.4"
      - name: Set up Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --snapshot --clean
