name: Publish Odiglet Base Builder

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The new image tag for the base builder docker image (e.g. v1.0)"
        required: true

permissions: read-all

env:
  DOCKERHUB_ORG: "keyval"

jobs:
  publish-odiglet-base-builder:
    runs-on: depot-ubuntu-24.04-8
    permissions:
      id-token: write


    steps:
      
      - name: Validate New Version
        run: |
          # Fetch tags from Docker Hub
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ env.DOCKERHUB_ORG }}/odiglet-base/tags/" | jq -r '.results[].name' | sort -Vr)

          # Extract the latest version
          LATEST_VERSION=$(echo "$TAGS" | head -n 1)

          # New version from workflow input
          NEW_VERSION=${{ github.event.inputs.image_tag }}

          # Parse major and minor from latest and new versions
          LATEST_MAJOR=$(echo $LATEST_VERSION | cut -d. -f1)
          LATEST_MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
          NEW_MAJOR=$(echo $NEW_VERSION | cut -d. -f1)
          NEW_MINOR=$(echo $NEW_VERSION | cut -d. -f2)

          # Compare versions
          if [[ $NEW_MAJOR -eq $((LATEST_MAJOR + 1)) && $NEW_MINOR -eq 0 ]]; then
            echo "New version is a valid major version increment."
          elif [[ $NEW_MAJOR -eq $LATEST_MAJOR && $NEW_MINOR -eq $((LATEST_MINOR + 1)) ]]; then
            echo "New version is a valid minor version increment."
          else
            echo "Error: New version $NEW_VERSION does not follow the versioning rules."
            exit 1
          fi

      - name: Get ro Token for this repo
        id: sts-this-repo
        uses: odigos-io/ci-core/sts@main
        with:
          scope: odigos-io/odigos
          identity: ro
          output-git-config: "false"

      - uses: actions/checkout@v6
        with:
          token: ${{ steps.sts-this-repo.outputs.GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: gcp-auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 1200s

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Publish Odiglet Base Builder
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./odiglet/base.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_ORG }}/odiglet-base:${{ github.event.inputs.image_tag }}
            ${{ env.DOCKERHUB_ORG }}/odiglet-base:latest
            us-central1-docker.pkg.dev/odigos-cloud/components/odiglet-base:${{ github.event.inputs.image_tag }}
      
      - name: Notify Slack
        uses: odigos-io/ci-core/.github/actions/slack-release-notification@main
        with:
          webhook-url: ${{ secrets.ODIGOS_RELEASE_STATUS_WEBHOOK_URL }}
          success-description: "Successfully published new Odiglet Base Builder image ${{ github.event.inputs.image_tag }}"
          failure-description: "ERROR: Failed to publish a new Odiglet Base Builder image ${{ github.event.inputs.image_tag }}"
          tag: ${{ github.event.inputs.image_tag }}

  update-odiglet-dockerfiles:
    needs: publish-odiglet-base-builder
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

      - name: Get ro Token for this repo
        id: sts-this-repo
        uses: odigos-io/ci-core/sts@main
        with:
          scope: odigos-io/odigos
          identity: ro
          output-git-config: "false"

      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ steps.sts-this-repo.outputs.GH_TOKEN }}

      - name: Update Odiglet Base Builder image in dockerfiles
        run: |
          sed -i "s|registry.odigos.io/odiglet-base:.*|registry.odigos.io/odiglet-base:${{ github.event.inputs.image_tag }}|g" odiglet/Dockerfile
          sed -i "s|registry.odigos.io/odiglet-base:.*|registry.odigos.io/odiglet-base:${{ github.event.inputs.image_tag }}|g" odiglet/debug.Dockerfile        

      - name: Create PR token
        id: create-pr-sts
        uses: odigos-io/ci-core/sts@main
        with:
          scope: odigos-io/odigos
          identity: create-pr
          output-git-config: true

      - name: Open a PR to update the Odiglet Base Builder image
        uses: peter-evans/create-pull-request@v8
        id: create-pr
        with:
          token: ${{ steps.create-pr-sts.outputs.GH_TOKEN }}
          title: "Update Odiglet Base Builder image to ${{ github.event.inputs.image_tag }}"
          body: "This is an automated PR generated after a new release of the odiglet base builder, to update it's version in odiglet dockerfiles to ${{ github.event.inputs.image_tag }}"
          base: "main"
          commit-message: "Update Odiglet Base Builder image to ${{ github.event.inputs.image_tag }}"
          labels: |
            automated
          delete-branch: true
      
      - name: Enable Pull Request Automerge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.create-pr-sts.outputs.GH_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash

      - name: Notify Slack
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: odigos-io/ci-core/.github/actions/slack-release-notification@main
        with:
          webhook-url: ${{ secrets.ODIGOS_RELEASE_STATUS_WEBHOOK_URL }}
          success-description: "Successfully created PR to update the Odiglet Base Builder image to ${{ github.event.inputs.image_tag }}: ${{ steps.create-pr.outputs.pull-request-url }}"
          failure-description: "ERROR: Failed to create PR to update the Odiglet Base Builder image to ${{ github.event.inputs.image_tag }}"
          tag: ${{ github.event.inputs.image_tag }}
